import type { GlobalConfig } from 'payload'

export const CalendarContent: GlobalConfig = {
  slug: 'calendar-content',
  admin: { group: 'Content' },
  access: { read: () => true },
  fields: [
    { name: 'title', type: 'text', defaultValue: 'Calendar' },
    {
      name: 'seriesConfirm',
      type: 'group',
      fields: [
        { name: 'detachTitle', type: 'text', defaultValue: 'Detach from recurrence?' },
        { name: 'detachBody', type: 'text', defaultValue: 'Moving this lesson to another day will detach it from the series. Other lessons in the series stay on their dates.' },
        { name: 'detachConfirm', type: 'text', defaultValue: 'Detach and move' },
        { name: 'applyAllTitle', type: 'text', defaultValue: 'Change all lessons in series?' },
        { name: 'applyAllBody', type: 'text', defaultValue: 'Are you sure you want to change the time for all scheduled lessons in this series?' },
        { name: 'applyAllConfirm', type: 'text', defaultValue: 'Change all' },
        { name: 'cancel', type: 'text', defaultValue: 'Cancel' },
      ],
    },
    {
      name: 'lessonModal',
      type: 'group',
      fields: [
        { name: 'titleCreate', type: 'text', defaultValue: 'Plan lesson' },
        { name: 'titleEdit', type: 'text', defaultValue: 'Edit lesson' },
        { name: 'subtitle', type: 'text', defaultValue: 'Configure lesson details, status and recurrence.' },
        {
          name: 'sections',
          type: 'group',
          fields: [
            { name: 'setup', type: 'text', defaultValue: 'Lesson planning' },
            { name: 'content', type: 'text', defaultValue: 'Lesson content' },
          ],
        },
        {
          name: 'fields',
          type: 'group',
          fields: [
            { name: 'title', type: 'text', defaultValue: 'Title' },
            { name: 'date', type: 'text', defaultValue: 'Date' },
            { name: 'startTime', type: 'text', defaultValue: 'Start time' },
            { name: 'duration', type: 'text', defaultValue: 'Duration (min)' },
            { name: 'recurrence', type: 'text', defaultValue: 'Recurrence' },
            { name: 'status', type: 'text', defaultValue: 'Status' },
            { name: 'cancelReason', type: 'text', defaultValue: 'Cancel reason' },
            { name: 'credited', type: 'text', defaultValue: 'Credited' },
            { name: 'weekDays', type: 'text', defaultValue: 'Week days' },
            { name: 'lessonType', type: 'text', defaultValue: 'Lesson type' },
            { name: 'studentGroup', type: 'text', defaultValue: 'Learning group' },
            { name: 'students', type: 'text', defaultValue: 'Students' },
            { name: 'student', type: 'text', defaultValue: 'Student' },
            { name: 'lessonPlan', type: 'text', defaultValue: 'Lesson plan' },
            { name: 'materials', type: 'text', defaultValue: 'Materials' },
            { name: 'homework', type: 'text', defaultValue: 'Homework' },
            { name: 'studentResponse', type: 'text', defaultValue: 'Student response' },
            { name: 'homeworkReview', type: 'text', defaultValue: 'Homework review' },
            { name: 'teacherHomeworkFeedback', type: 'text', defaultValue: 'Teacher feedback' },
          ],
        },
        {
          name: 'options',
          type: 'group',
          fields: [
            { name: 'noRepeat', type: 'text', defaultValue: 'No repeat' },
            { name: 'daily', type: 'text', defaultValue: 'Daily' },
            { name: 'weekly', type: 'text', defaultValue: 'Weekly' },
            { name: 'monthly', type: 'text', defaultValue: 'Monthly' },
            { name: 'planned', type: 'text', defaultValue: 'Planned' },
            { name: 'completed', type: 'text', defaultValue: 'Completed' },
            { name: 'cancelled', type: 'text', defaultValue: 'Cancelled' },
            { name: 'studentAbsent', type: 'text', defaultValue: 'Student absent' },
            { name: 'studentRequestedCancel', type: 'text', defaultValue: 'Student requested cancellation' },
            { name: 'teacherAbsent', type: 'text', defaultValue: 'Teacher absent' },
            { name: 'credited', type: 'text', defaultValue: 'Credited' },
            { name: 'notCredited', type: 'text', defaultValue: 'Not credited' },
            { name: 'individualLesson', type: 'text', defaultValue: 'Individual' },
            { name: 'groupLesson', type: 'text', defaultValue: 'Group' },
          ],
        },
        {
          name: 'hints',
          type: 'group',
          fields: [
            { name: 'recurrenceFixedOnly', type: 'text', defaultValue: 'Recurrence is available only for students with a fixed schedule.' },
          ],
        },
        {
          name: 'weekDays',
          type: 'group',
          fields: [
            { name: 'mon', type: 'text', defaultValue: 'Mon' },
            { name: 'tue', type: 'text', defaultValue: 'Tue' },
            { name: 'wed', type: 'text', defaultValue: 'Wed' },
            { name: 'thu', type: 'text', defaultValue: 'Thu' },
            { name: 'fri', type: 'text', defaultValue: 'Fri' },
            { name: 'sat', type: 'text', defaultValue: 'Sat' },
            { name: 'sun', type: 'text', defaultValue: 'Sun' },
          ],
        },
        {
          name: 'materialTypes',
          type: 'group',
          fields: [
            { name: 'text', type: 'text', defaultValue: 'Text' },
            { name: 'photo', type: 'text', defaultValue: 'Photo' },
            { name: 'test', type: 'text', defaultValue: 'Test' },
            { name: 'file', type: 'text', defaultValue: 'File' },
            { name: 'presentation', type: 'text', defaultValue: 'Presentation' },
            { name: 'book', type: 'text', defaultValue: 'Book' },
            { name: 'board', type: 'text', defaultValue: 'Board' },
          ],
        },
        {
          name: 'actions',
          type: 'group',
          fields: [
            { name: 'addFile', type: 'text', defaultValue: 'Add file' },
            { name: 'saveMaterial', type: 'text', defaultValue: 'Save material' },
            { name: 'cancel', type: 'text', defaultValue: 'Cancel' },
            { name: 'saveLesson', type: 'text', defaultValue: 'Save lesson' },
            { name: 'updateLesson', type: 'text', defaultValue: 'Update lesson' },
            { name: 'sendChangeRequest', type: 'text', defaultValue: 'Send change request' },
            { name: 'markHomeworkChecked', type: 'text', defaultValue: 'Mark as checked' },
          ],
        },
        {
          name: 'placeholders',
          type: 'group',
          fields: [
            { name: 'addText', type: 'text', defaultValue: 'Add text...' },
          ],
        },
        {
          name: 'messages',
          type: 'group',
          fields: [
            { name: 'blockedUnsafeFiles', type: 'text', defaultValue: 'Blocked unsafe files: {files}. Allowed: docs, slides, tables, text, images, pdf up to {max}MB.' },
            { name: 'rejectedFiles', type: 'text', defaultValue: 'Rejected: {files} (allowed up to {max}MB).' },
          ],
        },
        {
          name: 'aria',
          type: 'group',
          fields: [
            { name: 'sections', type: 'text', defaultValue: 'Lesson modal sections' },
            { name: 'unlinkSeries', type: 'text', defaultValue: 'Unlink lesson from series' },
            { name: 'deleteSeries', type: 'text', defaultValue: 'Delete all lessons in this series' },
            { name: 'deleteLesson', type: 'text', defaultValue: 'Delete lesson' },
            { name: 'closeModal', type: 'text', defaultValue: 'Close modal' },
            { name: 'removeFile', type: 'text', defaultValue: 'Remove file' },
            { name: 'removeMaterial', type: 'text', defaultValue: 'Remove material' },
            { name: 'closeImagePreview', type: 'text', defaultValue: 'Close image preview' },
          ],
        },
        { name: 'homeworkCheckedStatus', type: 'text', defaultValue: 'Checked' },
        { name: 'materialsHint', type: 'text', defaultValue: 'Choose type, fill details and save' },
        { name: 'noMaterials', type: 'text', defaultValue: 'No materials added yet.' },
        { name: 'fallbackMaterialLabel', type: 'text', defaultValue: 'Material' },
        { name: 'imagePreviewAlt', type: 'text', defaultValue: 'Material preview' },
      ],
    },
  ],
}
