ALTER TYPE "PaymentMethodKind" ADD VALUE IF NOT EXISTS 'WAYFORPAY';
ALTER TYPE "PaymentMethodKind" ADD VALUE IF NOT EXISTS 'LEMON_SQUEEZY';
ALTER TYPE "PaymentMethodKind" ADD VALUE IF NOT EXISTS 'PADDLE';
