import type { TourChapter } from './types';

/** Admin Tour v3 chapters — soft try-it scenarios after Level A. */
export const ADMIN_TOUR_CHAPTERS: TourChapter[] = [
  {
    id: 'adm-ch-create-learner',
    title: 'Create a learner',
    body: 'Open Admin and find the create-account form. Filling and saving is optional — Cancel / leave blank is fine.',
    area: 'Admin',
    pose: 'point',
    steps: [
      {
        id: 'adm-ch-create-open',
        level: 'B',
        title: 'Open Admin',
        body: 'Open Admin from the sidebar — create and remove accounts, plus bulk import.',
        area: 'Create learner',
        navHref: '/admin',
        pose: 'point',
        sfx: 'click',
        softSkipLabel: 'Skip for now',
        requiresAction: {
          id: 'adm-ch-create-open',
          hint: 'Open Admin from the sidebar.',
          detects: [{ kind: 'pathname', value: '/admin', match: 'startsWith' }],
        },
        uaIntent: 'Сторінка Admin',
      },
      {
        id: 'adm-ch-create-form',
        level: 'B',
        title: 'Find create form',
        body: 'Spot the create-account form. You can leave it empty — no need to submit.',
        area: 'Create learner',
        navHref: '/admin',
        anchorId: 'admin-create-form',
        pose: 'point',
        sfx: 'click',
        softSkipLabel: 'Skip for now',
        requiresAction: {
          id: 'adm-ch-create-form',
          hint: 'Find the create-account form on Admin.',
          detects: [{ kind: 'selector', value: '[data-tour-anchor="admin-create-form"]' }],
        },
        uaIntent: 'Форма створення акаунта',
      },
    ],
  },
  {
    id: 'adm-ch-student-payments',
    title: 'Student payments',
    body: 'Open System → Payments for methods and packages students use at checkout.',
    area: 'System',
    pose: 'point',
    steps: [
      {
        id: 'adm-ch-payments-system',
        level: 'B',
        title: 'Open System',
        body: 'Open System — the school control room.',
        area: 'Student payments',
        navHref: '/system',
        pose: 'point',
        sfx: 'click',
        softSkipLabel: 'Skip for now',
        requiresAction: {
          id: 'adm-ch-payments-system',
          hint: 'Open System from the sidebar.',
          detects: [{ kind: 'pathname', value: '/system', match: 'startsWith' }],
        },
        uaIntent: 'System',
      },
      {
        id: 'adm-ch-payments-tab',
        level: 'B',
        title: 'Payments tab',
        body: 'Switch to the Payments tab. Configure methods later — peeking is enough now.',
        area: 'Student payments',
        navHref: '/system',
        // Spotlight the tab trigger (panel `system-tab-payments` only mounts after click).
        anchorId: 'system-tab-payments-trigger',
        pose: 'point',
        sfx: 'click',
        softSkipLabel: 'Skip for now',
        requiresAction: {
          id: 'adm-ch-payments-tab',
          hint: 'Open System → Payments.',
          detects: [{ kind: 'selector', value: '[data-tour-anchor="system-tab-payments"]' }],
        },
        uaIntent: 'System → Payments',
      },
    ],
  },
  {
    id: 'adm-ch-subscription',
    title: 'School subscription',
    body: 'Open Subscription (Billing) — your school plan with Arvilio, not student lesson packs.',
    area: 'Subscription',
    pose: 'point',
    steps: [
      {
        id: 'adm-ch-billing-open',
        level: 'B',
        title: 'Open Subscription',
        body: 'Open Subscription from the sidebar to see seats, storage, and plan.',
        area: 'Subscription',
        navHref: '/billing',
        pose: 'point',
        sfx: 'click',
        softSkipLabel: 'Skip for now',
        requiresAction: {
          id: 'adm-ch-billing-open',
          hint: 'Open Subscription from the sidebar.',
          detects: [{ kind: 'pathname', value: '/billing', match: 'startsWith' }],
        },
        uaIntent: 'SaaS підписка',
      },
      {
        id: 'adm-ch-billing-plan',
        level: 'B',
        title: 'Current plan',
        body: 'Find the current plan card — upgrade and promos live here when needed.',
        area: 'Subscription',
        navHref: '/billing',
        anchorId: 'billing-plan',
        pose: 'point',
        sfx: 'click',
        softSkipLabel: 'Skip for now',
        requiresAction: {
          id: 'adm-ch-billing-plan',
          hint: 'Find the current plan on Subscription.',
          detects: [{ kind: 'selector', value: '[data-tour-anchor="billing-plan"]' }],
        },
        uaIntent: 'Картка плану',
      },
    ],
  },
  {
    id: 'adm-ch-finance',
    title: 'Finance peek',
    body: 'Open Finance for teacher payouts. Spot Record payout — do not submit.',
    area: 'Finance',
    pose: 'point',
    steps: [
      {
        id: 'adm-ch-finance-open',
        level: 'B',
        title: 'Open Finance',
        body: 'Open Finance from the sidebar — money out to teachers.',
        area: 'Finance',
        navHref: '/finance',
        pose: 'point',
        sfx: 'click',
        softSkipLabel: 'Skip for now',
        requiresAction: {
          id: 'adm-ch-finance-open',
          hint: 'Open Finance from the sidebar.',
          detects: [{ kind: 'pathname', value: '/finance', match: 'startsWith' }],
        },
        uaIntent: 'Фінанси',
      },
      {
        id: 'adm-ch-finance-payout',
        level: 'B',
        title: 'Record payout control',
        body: 'Find a Record payout control. Opening the form is optional; do not submit.',
        area: 'Finance',
        navHref: '/finance',
        anchorId: 'finance-record-payout',
        pose: 'point',
        sfx: 'click',
        softSkipLabel: 'Skip for now',
        requiresAction: {
          id: 'adm-ch-finance-payout',
          hint: 'Find Record payout on Finance (or skip if the table is empty).',
          detects: [
            { kind: 'selector', value: '[data-tour-anchor="finance-record-payout"]' },
            { kind: 'pathname', value: '/finance', match: 'startsWith' },
          ],
        },
        uaIntent: 'Record payout',
      },
    ],
  },
  {
    id: 'adm-ch-staff',
    title: 'Staff roster',
    body: 'Open Staff to see teachers and compensation cards.',
    area: 'Staff',
    pose: 'point',
    steps: [
      {
        id: 'adm-ch-staff-open',
        level: 'B',
        title: 'Open Staff',
        body: 'Open Staff from the sidebar.',
        area: 'Staff',
        navHref: '/staff',
        pose: 'point',
        sfx: 'click',
        softSkipLabel: 'Skip for now',
        requiresAction: {
          id: 'adm-ch-staff-open',
          hint: 'Open Staff from the sidebar.',
          detects: [{ kind: 'pathname', value: '/staff', match: 'startsWith' }],
        },
        uaIntent: 'Персонал',
      },
      {
        id: 'adm-ch-staff-roster',
        level: 'B',
        title: 'Staff list',
        body: 'Browse staff cards — open someone later for compensation settings.',
        area: 'Staff',
        navHref: '/staff',
        anchorId: 'staff-roster',
        pose: 'point',
        sfx: 'click',
        softSkipLabel: 'Skip for now',
        requiresAction: {
          id: 'adm-ch-staff-roster',
          hint: 'Find the staff roster on Staff.',
          detects: [
            { kind: 'selector', value: '[data-tour-anchor="staff-roster"]' },
            { kind: 'pathname', value: '/staff', match: 'startsWith' },
          ],
        },
        uaIntent: 'Список персоналу',
      },
    ],
  },
];
