import type { TourStep } from './types';

/**
 * Admin Level A — ops map after school wizard.
 * Money: Payment (students) ≠ Subscription ≠ System Payments ≠ Finance.
 */
export const ADMIN_TOUR_STEPS: TourStep[] = [
  {
    id: 'adm-welcome',
    title: 'Your school workspace',
    body: "I'm Arvi. Next: people, subscription, and system settings. If you already used the wizard, we won't repeat those forms. Replay later from Profile → Account.",
    pose: 'greet',
    uaIntent: 'Привітання після wizard',
  },
  {
    id: 'adm-dashboard',
    title: 'School dashboard',
    body: 'Your pulse page — teaching shortcuts plus an entitlements meter for seats and storage that mirrors Subscription.',
    area: 'Dashboard',
    navHref: '/dashboard',
    anchorId: 'dash-hero',
    pose: 'point',
    uaIntent: 'Дашборд + entitlements',
  },
  {
    id: 'adm-entitlements',
    title: 'Seats & storage',
    body: 'The entitlements meter tracks plan seats and storage. Open Subscription to upgrade or apply a promo.',
    area: 'Dashboard',
    navHref: '/dashboard',
    anchorId: 'dash-entitlements',
    pose: 'point',
    uaIntent: 'Entitlements на дашборді',
  },
  {
    id: 'adm-students',
    title: 'Students & groups',
    body: 'Manage learners here. Open a profile for progress, practice, and lesson balance. Groups appear when System → General has group lessons on.',
    area: 'Students',
    navHref: '/students',
    pose: 'point',
    uaIntent: 'Учні / групи',
  },
  {
    id: 'adm-groups',
    title: 'Groups',
    body: 'When group lessons are enabled, switch to Groups for templates and members.',
    area: 'Students',
    navHref: '/students',
    anchorId: 'students-groups-tab',
    pose: 'point',
    uaIntent: 'Groups tab',
    requiresFeature: 'groupLessons',
  },
  {
    id: 'adm-admin',
    title: 'Create accounts',
    body: 'Admin creates and removes accounts and supports bulk student import. Temporary passwords go out by email. Seat limits can block new students — use the form below the metrics.',
    area: 'Admin',
    navHref: '/admin',
    anchorId: 'admin-create-form',
    pose: 'point',
    uaIntent: 'Створення акаунтів',
  },
  {
    id: 'adm-staff',
    title: 'Staff',
    body: 'Teachers and staff cards — open someone for compensation settings and earnings history. Pair with Finance when you record payouts.',
    area: 'Staff',
    navHref: '/staff',
    pose: 'point',
    uaIntent: 'Персонал',
  },
  {
    id: 'adm-billing',
    title: 'School subscription',
    body: "Billing (Subscription in the nav) is your school's plan with Arvilio — seats, storage, trial, promos. Not where students buy lesson packs.",
    area: 'Subscription',
    navHref: '/billing',
    pose: 'point',
    uaIntent: 'SaaS підписка',
  },
  {
    id: 'adm-system',
    title: 'System overview',
    body: 'System is the control room: General, Email, Dictionary, Connections, Payments, Payouts, Domains, Branding.',
    area: 'System',
    navHref: '/system',
    pose: 'point',
    uaIntent: 'System огляд',
  },
  {
    id: 'adm-system-payments',
    title: 'Payments for students',
    body: 'Open System → Payments for methods, packages, and invoice templates. Students only see checkout on Payment after this is configured. Peeking at the tab is enough for now.',
    area: 'System',
    navHref: '/system',
    anchorId: 'system-tab-payments-trigger',
    pose: 'point',
    uaIntent: 'System → Payments',
  },
  {
    id: 'adm-system-general',
    title: 'Group lessons & video',
    body: 'System → General toggles group lessons (unlocks Students → Groups) and the video meetings provider panel.',
    area: 'System',
    navHref: '/system',
    pose: 'point',
    uaIntent: 'General: groups + video',
  },
  {
    id: 'adm-materials',
    title: 'School materials',
    body: 'Shared library for boards, books, and media. Storage counts against your subscription quota.',
    area: 'Materials',
    navHref: '/materials',
    anchorId: 'materials-create',
    pose: 'point',
    uaIntent: 'Матеріали',
  },
  {
    id: 'adm-finance',
    title: 'Finance & payouts',
    body: 'School money-out to teachers — charts, history, Record payout. Rates live under Staff; defaults under System → Payouts.',
    area: 'Finance',
    navHref: '/finance',
    pose: 'point',
    uaIntent: 'Фінанси',
  },
  {
    id: 'adm-calendar',
    title: 'School calendar',
    body: 'See the whole schedule; filter audience and teachers. Admins can plan lessons too.',
    area: 'Calendar',
    navHref: '/calendar',
    pose: 'point',
    uaIntent: 'Календар школи',
  },
  {
    id: 'adm-chat',
    title: 'Chat',
    body: 'Message staff and students. Admins can also create group chats.',
    area: 'Chat',
    navHref: '/chat',
    anchorId: 'chat-new-message',
    pose: 'point',
    uaIntent: 'Чат / group chat',
  },
  {
    id: 'adm-profile',
    title: 'Your profile',
    body: 'Personal settings, appearance, and connections. Replay this tour from the Account tab anytime.',
    area: 'Profile',
    navHref: '/profile',
    pose: 'point',
    uaIntent: 'Профіль адміна',
  },
  {
    id: 'adm-done',
    title: "You're set",
    body: "You've walked every main section. Next: try short scenarios — create a learner, Payments, Subscription, and more.",
    pose: 'celebrate',
    uaIntent: 'Фініш → chapters',
  },
];
