import type { TourStep } from './types';

/**
 * Teacher Help encyclopedia (Header `?`) — TZ §4.13.4.
 */
export const TEACHER_HELP_STEPS: TourStep[] = [
  // /dashboard
  {
    id: 'help-tea-dash-hero',
    title: 'Teaching hub',
    body: "Start each day here: today's lessons, homework waiting for review, and shortcuts including New lesson and Students.",
    area: 'Dashboard',
    navHref: '/dashboard',
    anchorId: 'dash-hero',
    pose: 'point',
    uaIntent: 'Герой викладача',
  },
  {
    id: 'help-tea-dash-quick-actions',
    title: 'Quick actions',
    body: 'Jump to Calendar, Students, Materials, Chat, or create a lesson without hunting the sidebar.',
    area: 'Dashboard',
    navHref: '/dashboard',
    anchorId: 'dash-quick-actions',
    pose: 'point',
    uaIntent: 'Швидкі дії',
  },
  {
    id: 'help-tea-dash-homework',
    title: 'Homework to review',
    body: 'When students submit after a completed lesson, items appear here. Open a lesson to accept or leave feedback.',
    area: 'Dashboard',
    navHref: '/dashboard',
    anchorId: 'dash-homework-review',
    pose: 'point',
    uaIntent: 'Черга ДЗ',
  },
  {
    id: 'help-tea-dash-today',
    title: "Today's lessons",
    body: 'Your schedule for today. Open a card to enter the lesson room.',
    area: 'Dashboard',
    navHref: '/dashboard',
    anchorId: 'dash-today-lessons',
    pose: 'point',
    uaIntent: 'Уроки сьогодні',
  },
  {
    id: 'help-tea-dash-week',
    title: 'This week',
    body: 'Broader week view of planned lessons.',
    area: 'Dashboard',
    navHref: '/dashboard',
    anchorId: 'dash-week-lessons',
    pose: 'point',
    uaIntent: 'Уроки тижня',
  },
  {
    id: 'help-tea-dash-students',
    title: 'My students',
    body: 'Snapshot of learners assigned to you. Open Students for the full roster.',
    area: 'Dashboard',
    navHref: '/dashboard',
    anchorId: 'dash-my-students',
    pose: 'point',
    uaIntent: 'Мої учні',
  },
  {
    id: 'help-tea-dash-month',
    title: 'Lessons this month',
    body: 'Monthly volume for a quick capacity check.',
    area: 'Dashboard',
    navHref: '/dashboard',
    anchorId: 'dash-lessons-month',
    pose: 'point',
    uaIntent: 'Уроки за місяць',
  },
  // /calendar
  {
    id: 'help-tea-cal-toolbar',
    title: 'Week or month',
    body: 'Switch views and navigate dates. Past slots stay locked; timezone follows your Profile.',
    area: 'Calendar',
    navHref: '/calendar',
    anchorId: 'calendar-toolbar',
    pose: 'point',
    uaIntent: 'Тулбар',
  },
  {
    id: 'help-tea-cal-grid',
    title: 'Plan on the board',
    body: 'Create, move, and resize lessons. Conflicts and series edits confirm separately.',
    area: 'Calendar',
    navHref: '/calendar',
    anchorId: 'calendar-grid',
    pose: 'point',
    uaIntent: 'DnD сітка',
  },
  {
    id: 'help-tea-cal-create',
    title: 'New lesson',
    body: 'Header Create lesson (or calendar empty slot) opens the modal: Setup, Content, Homework — cancel anytime without saving.',
    area: 'Calendar',
    navHref: '/calendar',
    anchorId: 'header-create-lesson',
    pose: 'point',
    uaIntent: 'CTA створення',
  },
  {
    id: 'help-tea-cal-modal',
    title: 'Lesson modal',
    body: 'Setup who/when; Content attaches library materials; Homework sets student work.',
    area: 'Calendar',
    navHref: '/calendar',
    anchorId: 'lesson-modal',
    pose: 'point',
    uaIntent: 'Модалка уроку',
  },
  // /lessons
  {
    id: 'help-tea-lessons-highlights',
    title: 'Highlights',
    body: 'Next/previous cards with materials and homework badges.',
    area: 'Lessons',
    navHref: '/lessons',
    anchorId: 'lessons-highlights',
    pose: 'point',
    uaIntent: 'Хайлайти',
  },
  {
    id: 'help-tea-lessons-list',
    title: 'Lessons list',
    body: 'Filter and open any lesson you teach. Create/edit from here or the calendar.',
    area: 'Lessons',
    navHref: '/lessons',
    anchorId: 'lessons-list',
    pose: 'point',
    uaIntent: 'Список',
  },
  {
    id: 'help-tea-lesson-plan',
    title: 'Lesson plan',
    body: 'Edit the plan students see in the lesson room.',
    area: 'Lessons',
    navHref: '/lessons',
    anchorId: 'lesson-plan',
    pose: 'point',
    uaIntent: 'План уроку',
  },
  {
    id: 'help-tea-lesson-join',
    title: 'Join video',
    body: 'Host Meet/Zoom/LiveKit when Connections and System video provider are ready.',
    area: 'Lessons',
    navHref: '/lessons',
    anchorId: 'lesson-join-video',
    pose: 'point',
    uaIntent: 'Відео',
  },
  {
    id: 'help-tea-lesson-homework',
    title: 'Review homework',
    body: 'Accept or feedback student submissions after the lesson is completed.',
    area: 'Lessons',
    navHref: '/lessons',
    anchorId: 'lesson-homework',
    pose: 'point',
    uaIntent: 'Перевірка ДЗ',
  },
  // /materials
  {
    id: 'help-tea-materials-grid',
    title: 'Library grid',
    body: 'Boards, books, audio, and video reusable across lessons. Students open files from lessons, not this library.',
    area: 'Materials',
    navHref: '/materials',
    anchorId: 'materials-grid',
    pose: 'point',
    uaIntent: 'Сітка бібліотеки',
  },
  {
    id: 'help-tea-materials-create',
    title: 'Add material',
    body: 'Create a library entry — links, uploads (≤100MB), metadata.',
    area: 'Materials',
    navHref: '/materials',
    anchorId: 'materials-create',
    pose: 'point',
    uaIntent: 'Створити матеріал',
  },
  {
    id: 'help-tea-materials-upload',
    title: 'Upload form',
    body: 'Fill the form and attach files. Interrupted uploads can resume via the recovery banner.',
    area: 'Materials',
    navHref: '/materials',
    anchorId: 'materials-upload',
    pose: 'point',
    uaIntent: 'Форма завантаження',
  },
  {
    id: 'help-tea-materials-viewer',
    title: 'Viewer',
    body: 'Books open in-app with annotations; media opens in a modal. Watch school storage quota.',
    area: 'Materials',
    navHref: '/materials',
    anchorId: 'materials-viewer',
    pose: 'point',
    uaIntent: 'Переглядач',
  },
  // /students
  {
    id: 'help-tea-students-list',
    title: 'Roster',
    body: 'Learners assigned to you. Empty state means nobody is assigned yet.',
    area: 'Students',
    navHref: '/students',
    anchorId: 'students-list',
    pose: 'point',
    uaIntent: 'Список учнів',
  },
  {
    id: 'help-tea-students-groups',
    title: 'Groups',
    body: 'When group lessons are on (System → General), switch here for shared templates and members.',
    area: 'Students',
    navHref: '/students',
    anchorId: 'students-groups-tab',
    pose: 'point',
    uaIntent: 'Вкладка Groups',
    requiresFeature: 'groupLessons',
  },
  {
    id: 'help-tea-students-card',
    title: 'Student card',
    body: 'Open a learner for Profile, Statistics, Lessons, Practice, and more. Teachers do not see student pricing.',
    area: 'Students',
    navHref: '/students',
    anchorId: 'student-card',
    pose: 'point',
    uaIntent: 'Картка учня',
  },
  {
    id: 'help-tea-student-practice',
    title: 'Assign practice',
    body: 'Practice tab: assign vocabulary, quizzes, or speaking.',
    area: 'Students',
    navHref: '/students',
    anchorId: 'student-practice-tab',
    pose: 'point',
    uaIntent: 'Practice tab',
  },
  {
    id: 'help-tea-student-dm',
    title: 'Message student',
    body: 'From the student hero, jump into a DM without hunting Chat.',
    area: 'Students',
    navHref: '/students',
    anchorId: 'student-hero-chat',
    pose: 'point',
    uaIntent: 'DM з профілю',
  },
  // /chat
  {
    id: 'help-tea-chat-inbox',
    title: 'Inbox',
    body: 'Threads with your students and admins. Calendar “request lesson” lands here.',
    area: 'Chat',
    navHref: '/chat',
    anchorId: 'chat-inbox',
    pose: 'point',
    uaIntent: 'Інбокс',
  },
  {
    id: 'help-tea-chat-new',
    title: 'New message',
    body: 'Start a DM with an assigned student or admin.',
    area: 'Chat',
    navHref: '/chat',
    anchorId: 'chat-new-message',
    pose: 'point',
    uaIntent: 'Нове повідомлення',
  },
  {
    id: 'help-tea-chat-composer',
    title: 'Thread',
    body: 'Reply and attach files (24h TTL).',
    area: 'Chat',
    navHref: '/chat',
    anchorId: 'chat-composer',
    pose: 'point',
    uaIntent: 'Композер',
  },
  // /profile
  {
    id: 'help-tea-profile-tab',
    title: 'Profile',
    body: 'Your teaching identity, timezone, and languages.',
    area: 'Profile',
    navHref: '/profile',
    anchorId: 'profile-tab-profile',
    pose: 'point',
    uaIntent: 'Profile',
  },
  {
    id: 'help-tea-profile-stats',
    title: 'Statistics',
    body: 'Teaching metrics; earnings glance may appear here — not school Finance.',
    area: 'Profile',
    navHref: '/profile',
    anchorId: 'profile-tab-statistics',
    pose: 'point',
    uaIntent: 'Статистика / earnings',
  },
  {
    id: 'help-tea-profile-notifications',
    title: 'Notifications',
    body: 'Email and in-app prefs.',
    area: 'Profile',
    navHref: '/profile',
    anchorId: 'profile-tab-notifications',
    pose: 'point',
    uaIntent: 'Сповіщення',
  },
  {
    id: 'help-tea-profile-connections',
    title: 'Connections',
    body: 'Link Google or Zoom so you can host video lessons.',
    area: 'Profile',
    navHref: '/profile',
    anchorId: 'profile-connections',
    pose: 'point',
    uaIntent: 'OAuth для відео',
  },
  {
    id: 'help-tea-profile-appearance',
    title: 'Appearance',
    body: 'Theme and font size.',
    area: 'Profile',
    navHref: '/profile',
    anchorId: 'profile-tab-appearance',
    pose: 'point',
    uaIntent: 'Appearance',
  },
  {
    id: 'help-tea-profile-account',
    title: 'Account',
    body: 'Learning mode, Replay tour, password, logout.',
    area: 'Profile',
    navHref: '/profile',
    anchorId: 'profile-tab-account',
    pose: 'point',
    uaIntent: 'Account',
  },
  // /practice + modes (full hub; assign from student profiles)
  {
    id: 'help-tea-practice-hub',
    title: 'Practice hub',
    body: 'Preview learner modes here. Assign vocabulary, quizzes, or speaking from a student’s Practice tab.',
    area: 'Practice',
    navHref: '/practice',
    anchorId: 'practice-hub-cards',
    pose: 'point',
    uaIntent: 'Хаб практики',
  },
  {
    id: 'help-tea-practice-stats',
    title: 'Week stats',
    body: 'When you practice as staff, week activity shows here the same way it does for learners.',
    area: 'Practice',
    navHref: '/practice',
    anchorId: 'practice-stats',
    pose: 'point',
    uaIntent: 'Статистика тижня',
  },
  {
    id: 'help-tea-practice-vocab',
    title: 'Vocabulary',
    body: 'Open Vocabulary to preview list, flashcards, and Play. Assign decks from the student’s Practice tab.',
    area: 'Vocabulary',
    navHref: '/practice',
    anchorId: 'practice-card-vocabulary',
    pose: 'point',
    uaIntent: 'Картка Vocabulary',
  },
  {
    id: 'help-tea-vocab-modes',
    title: 'List · Flashcards · Play',
    body: 'Switch study modes while previewing a deck. Play needs enough cards — same rules as for learners.',
    area: 'Vocabulary',
    navHref: '/vocabulary',
    anchorId: 'vocab-mode-toggle',
    pose: 'point',
    uaIntent: 'Режими словника',
  },
  {
    id: 'help-tea-vocab-stats',
    title: 'Deck stats',
    body: 'New / review / learned counts for the deck you are previewing.',
    area: 'Vocabulary',
    navHref: '/vocabulary',
    anchorId: 'vocab-stats',
    pose: 'point',
    uaIntent: 'Статистика колоди',
  },
  {
    id: 'help-tea-vocab-add',
    title: 'Add a word',
    body: 'Try the add-word flow; learner decks are usually filled from lessons or your assignments.',
    area: 'Vocabulary',
    navHref: '/vocabulary',
    anchorId: 'vocab-add-word',
    pose: 'point',
    uaIntent: 'Додати слово',
  },
  {
    id: 'help-tea-vocab-filters',
    title: 'Search & filters',
    body: 'Find words by text, lesson, or part of speech while previewing a deck.',
    area: 'Vocabulary',
    navHref: '/vocabulary',
    anchorId: 'vocab-filters',
    pose: 'point',
    uaIntent: 'Фільтри словника',
  },
  {
    id: 'help-tea-vocab-list',
    title: 'Card grid',
    body: 'Preview learner cards and statuses. Assign decks from the student’s Practice tab.',
    area: 'Vocabulary',
    navHref: '/vocabulary',
    anchorId: 'vocab-word-list',
    pose: 'point',
    uaIntent: 'Сітка карток',
  },
  {
    id: 'help-tea-vocab-flashcard',
    title: 'Flashcard',
    body: 'Same flip-and-mark flow learners use — useful when checking what students see.',
    area: 'Vocabulary',
    navHref: '/vocabulary',
    anchorId: 'vocab-flashcard',
    pose: 'point',
    uaIntent: 'Флешкартка',
  },
  {
    id: 'help-tea-vocab-play-setup',
    title: 'Play setup',
    body: 'Preview Play setup: choose a source, then start when the pool has enough cards.',
    area: 'Vocabulary',
    navHref: '/vocabulary',
    anchorId: 'vocab-play-setup',
    pose: 'point',
    uaIntent: 'Підготовка Play',
  },
  {
    id: 'help-tea-vocab-play-source',
    title: 'Word source',
    body: 'Random, last lesson, or a specific lesson — same controls learners get.',
    area: 'Vocabulary',
    navHref: '/vocabulary',
    anchorId: 'vocab-play-source',
    pose: 'point',
    uaIntent: 'Джерело слів',
  },
  {
    id: 'help-tea-vocab-play-start',
    title: 'Start Play',
    body: 'Begins a multiple-choice preview round.',
    area: 'Vocabulary',
    navHref: '/vocabulary',
    anchorId: 'vocab-play-start',
    pose: 'point',
    uaIntent: 'Старт Play',
  },
  {
    id: 'help-tea-vocab-play-progress',
    title: 'Round progress',
    body: 'Question number and score dots during a Play round.',
    area: 'Vocabulary',
    navHref: '/vocabulary',
    anchorId: 'vocab-play-progress',
    pose: 'point',
    uaIntent: 'Прогрес раунду',
  },
  {
    id: 'help-tea-vocab-play-question',
    title: 'Prompt',
    body: 'The English word shown during Play.',
    area: 'Vocabulary',
    navHref: '/vocabulary',
    anchorId: 'vocab-play-question',
    pose: 'point',
    uaIntent: 'Питання',
  },
  {
    id: 'help-tea-vocab-play-options',
    title: 'Answer choices',
    body: 'Multiple-choice options — same interaction as for learners.',
    area: 'Vocabulary',
    navHref: '/vocabulary',
    anchorId: 'vocab-play-options',
    pose: 'point',
    uaIntent: 'Варіанти відповіді',
  },
  {
    id: 'help-tea-vocab-play-actions',
    title: 'Check · Next · Finish',
    body: 'Confirm, advance, or end the round early.',
    area: 'Vocabulary',
    navHref: '/vocabulary',
    anchorId: 'vocab-play-actions',
    pose: 'point',
    uaIntent: 'Дії раунду',
  },
  {
    id: 'help-tea-vocab-play-result',
    title: 'Round results',
    body: 'Score summary and New round after Play finishes.',
    area: 'Vocabulary',
    navHref: '/vocabulary',
    anchorId: 'vocab-play-result',
    pose: 'point',
    uaIntent: 'Результат раунду',
  },
  {
    id: 'help-tea-practice-quiz',
    title: 'Quizzes',
    body: 'Open Quiz to preview assigned vs practice runs. Generate quizzes from the quiz hub when available.',
    area: 'Quiz',
    navHref: '/practice',
    anchorId: 'practice-card-quiz',
    pose: 'point',
    uaIntent: 'Вікторини',
  },
  {
    id: 'help-tea-quiz-hero',
    title: 'Quiz session',
    body: 'Inside a quiz: answer flow matches learners.',
    area: 'Quiz',
    navHref: '/quiz',
    anchorId: 'quiz-hero',
    pose: 'point',
    uaIntent: 'Сесія квізу',
  },
  {
    id: 'help-tea-practice-quiz-gen',
    title: 'Generate quizzes',
    body: 'Create quizzes for learners from the quiz hub. Assign them from the student’s Practice tab.',
    area: 'Quiz',
    navHref: '/quiz',
    anchorId: 'quiz-generate',
    pose: 'point',
    uaIntent: 'Генерація квізів',
  },
  {
    id: 'help-tea-practice-speaking',
    title: 'Speaking',
    body: 'Preview speaking topics and recording. Assign topics and review submissions from the student’s Practice tab.',
    area: 'Speaking',
    navHref: '/practice',
    anchorId: 'practice-card-speaking',
    pose: 'point',
    uaIntent: 'Speaking',
  },
  {
    id: 'help-tea-speaking-record',
    title: 'Record a reply',
    body: 'Mic permission is required to record. You review learner submissions later.',
    area: 'Speaking',
    navHref: '/practice/speaking',
    anchorId: 'speaking-record',
    pose: 'point',
    uaIntent: 'Запис Speaking',
  },
  {
    id: 'help-tea-practice-irregular',
    title: 'Irregular verbs',
    body: 'Three-forms drill for preview. Results are not saved to a vocabulary deck; they count toward practice week time.',
    area: 'Irregular verbs',
    navHref: '/practice',
    anchorId: 'practice-card-irregular',
    pose: 'point',
    uaIntent: 'Неправильні дієслова',
  },
  {
    id: 'help-tea-irregular-play',
    title: 'Start a drill',
    body: 'Pick a tier, then Play — same drill learners use.',
    area: 'Irregular verbs',
    navHref: '/practice/irregular-verbs',
    anchorId: 'irregular-play',
    pose: 'point',
    uaIntent: 'Старт drill',
  },
];
