import type { TourStep } from './types';

/**
 * Admin Help encyclopedia (Header `?`) — TZ §4.13.5.
 * Also used for super_admin Help (Level A stays admin_platform).
 */
export const ADMIN_HELP_STEPS: TourStep[] = [
  // /dashboard
  {
    id: 'help-adm-dash-hero',
    title: 'School pulse',
    body: 'Daily hub for the school — teaching shortcuts plus ops signals.',
    area: 'Dashboard',
    navHref: '/dashboard',
    anchorId: 'dash-hero',
    pose: 'point',
    uaIntent: 'Герой школи',
  },
  {
    id: 'help-adm-dash-quick-actions',
    title: 'Quick actions',
    body: 'Jump to Students, Calendar, New lesson, Admin, or Subscription.',
    area: 'Dashboard',
    navHref: '/dashboard',
    anchorId: 'dash-quick-actions',
    pose: 'point',
    uaIntent: 'Швидкі дії',
  },
  {
    id: 'help-adm-dash-homework',
    title: 'Homework queue',
    body: 'Same staff queue as teachers when you teach or review.',
    area: 'Dashboard',
    navHref: '/dashboard',
    anchorId: 'dash-homework-review',
    pose: 'point',
    uaIntent: 'Черга ДЗ',
  },
  {
    id: 'help-adm-dash-today',
    title: "Today's lessons",
    body: 'School-wide or your teaching schedule depending on filters.',
    area: 'Dashboard',
    navHref: '/dashboard',
    anchorId: 'dash-today-lessons',
    pose: 'point',
    uaIntent: 'Уроки сьогодні',
  },
  {
    id: 'help-adm-dash-entitlements',
    title: 'Seats & storage',
    body: 'Plan seats and storage meter — mirrors Subscription (/billing). Upgrade there if you are near limits.',
    area: 'Dashboard',
    navHref: '/dashboard',
    anchorId: 'dash-entitlements',
    pose: 'point',
    uaIntent: 'Entitlements',
  },
  {
    id: 'help-adm-dash-stats',
    title: 'School stats',
    body: 'Quick tiles for today’s teaching load and school pulse metrics.',
    area: 'Dashboard',
    navHref: '/dashboard',
    anchorId: 'dash-stats',
    pose: 'point',
    uaIntent: 'Плитки статистики',
  },
  {
    id: 'help-adm-dash-week',
    title: 'This week',
    body: 'Broader week view of planned lessons across the school.',
    area: 'Dashboard',
    navHref: '/dashboard',
    anchorId: 'dash-week-lessons',
    pose: 'point',
    uaIntent: 'Уроки тижня',
  },
  {
    id: 'help-adm-dash-students',
    title: 'Learners snapshot',
    body: 'Recent learners assigned in this school. Open Students for the full roster.',
    area: 'Dashboard',
    navHref: '/dashboard',
    anchorId: 'dash-my-students',
    pose: 'point',
    uaIntent: 'Знімок учнів',
  },
  {
    id: 'help-adm-dash-month',
    title: 'Lessons this month',
    body: 'Monthly volume for a quick capacity check.',
    area: 'Dashboard',
    navHref: '/dashboard',
    anchorId: 'dash-lessons-month',
    pose: 'point',
    uaIntent: 'Уроки за місяць',
  },
  // /students
  {
    id: 'help-adm-students-list',
    title: 'Learners roster',
    body: 'Learning roster — progress, practice, and lesson balance on each profile. Account create/delete is under Admin.',
    area: 'Students',
    navHref: '/students',
    anchorId: 'students-list',
    pose: 'point',
    uaIntent: 'Ростер учнів',
  },
  {
    id: 'help-adm-students-groups',
    title: 'Groups',
    body: 'Shared templates and members when group lessons are enabled in System → General.',
    area: 'Students',
    navHref: '/students',
    anchorId: 'students-groups-tab',
    pose: 'point',
    uaIntent: 'Groups',
    requiresFeature: 'groupLessons',
  },
  {
    id: 'help-adm-students-panel',
    title: 'Groups panel',
    body: 'Manage group membership and templates used when scheduling group lessons.',
    area: 'Students',
    navHref: '/students',
    anchorId: 'students-groups-panel',
    pose: 'point',
    uaIntent: 'Панель груп',
    requiresFeature: 'groupLessons',
  },
  {
    id: 'help-adm-student-billing',
    title: 'Student billing',
    body: "Adjust a learner’s lesson balance here. This is not school Subscription.",
    area: 'Students',
    navHref: '/students',
    anchorId: 'student-billing-tab',
    pose: 'point',
    uaIntent: 'Баланс учня',
  },
  {
    id: 'help-adm-student-practice',
    title: 'Assign practice',
    body: 'Same Practice tab as teachers — vocab, quiz, speaking.',
    area: 'Students',
    navHref: '/students',
    anchorId: 'student-practice-tab',
    pose: 'point',
    uaIntent: 'Practice',
  },
  {
    id: 'help-adm-student-profile',
    title: 'Open learner',
    body: 'Profile, statistics, lessons, achievements — full learner OS.',
    area: 'Students',
    navHref: '/students',
    anchorId: 'student-card',
    pose: 'point',
    uaIntent: 'Профіль учня',
  },
  // /admin
  {
    id: 'help-adm-admin-create',
    title: 'Create accounts',
    body: 'Create and remove accounts; temporary passwords go out by email. Seat limits can block new students.',
    area: 'Admin',
    navHref: '/admin',
    anchorId: 'admin-create-form',
    pose: 'point',
    uaIntent: 'Створення акаунтів',
  },
  {
    id: 'help-adm-admin-import',
    title: 'Bulk import',
    body: 'Import students in bulk when available. Distinct from the learning roster on Students.',
    area: 'Admin',
    navHref: '/admin',
    anchorId: 'admin-import',
    pose: 'point',
    uaIntent: 'Імпорт',
  },
  {
    id: 'help-adm-admin-seats',
    title: 'Seats',
    body: 'New learners consume Subscription seats — check Billing if create fails.',
    area: 'Admin',
    navHref: '/admin',
    anchorId: 'admin-seats-hint',
    pose: 'point',
    uaIntent: 'Ліміт місць',
  },
  // /staff
  {
    id: 'help-adm-staff-roster',
    title: 'Staff roster',
    body: 'Teachers and staff with compensation / earnings settings per person.',
    area: 'Staff',
    navHref: '/staff',
    anchorId: 'staff-roster',
    pose: 'point',
    uaIntent: 'Ростер staff',
  },
  {
    id: 'help-adm-staff-comp',
    title: 'Compensation',
    body: 'Pay settings for a person — not the same as Finance payouts ledger.',
    area: 'Staff',
    navHref: '/staff',
    anchorId: 'staff-compensation',
    pose: 'point',
    uaIntent: 'Компенсація',
  },
  {
    id: 'help-adm-staff-detail',
    title: 'Staff profile',
    body: 'Open a staff member for earnings history and setup.',
    area: 'Staff',
    navHref: '/staff',
    anchorId: 'staff-detail',
    pose: 'point',
    uaIntent: 'Картка staff',
  },
  // /billing
  {
    id: 'help-adm-billing-plan',
    title: 'School subscription',
    body: 'SaaS plan, seats, and storage for the school (Layer B). Never confuse with student /payment.',
    area: 'Subscription',
    navHref: '/billing',
    anchorId: 'billing-plan',
    pose: 'point',
    uaIntent: 'Підписка школи',
  },
  {
    id: 'help-adm-billing-usage',
    title: 'Usage & quotas',
    body: 'How seats and storage are consumed vs plan limits.',
    area: 'Subscription',
    navHref: '/billing',
    anchorId: 'billing-usage',
    pose: 'point',
    uaIntent: 'Використання',
  },
  {
    id: 'help-adm-billing-promo',
    title: 'Promo codes',
    body: 'Apply platform promo codes when offered.',
    area: 'Subscription',
    navHref: '/billing',
    anchorId: 'billing-promo',
    pose: 'point',
    uaIntent: 'Промо',
  },
  // /finance
  {
    id: 'help-adm-finance-overview',
    title: 'Finance overview',
    body: 'School money-out: charts and payout history to teachers.',
    area: 'Finance',
    navHref: '/finance',
    anchorId: 'finance-overview',
    pose: 'point',
    uaIntent: 'Огляд фінансів',
  },
  {
    id: 'help-adm-finance-payout',
    title: 'Record payout',
    body: 'Record a payout to staff. Soft peek is enough — you can cancel.',
    area: 'Finance',
    navHref: '/finance',
    anchorId: 'finance-record-payout',
    pose: 'point',
    uaIntent: 'Запис виплати',
  },
  {
    id: 'help-adm-finance-defaults',
    title: 'Payout defaults',
    body: 'Defaults often mirror System → Payouts.',
    area: 'Finance',
    navHref: '/finance',
    anchorId: 'finance-payout-defaults',
    pose: 'point',
    uaIntent: 'Дефолти виплат',
  },
  // /system
  {
    id: 'help-adm-system-overview',
    title: 'System control room',
    body: 'Integrations and school settings. Use the tabs for each area — Payments is critical for student checkout.',
    area: 'System',
    navHref: '/system',
    pose: 'point',
    uaIntent: 'Огляд System',
  },
  {
    id: 'help-adm-system-general',
    title: 'General',
    body: 'Group lessons toggle and video meetings provider for the school.',
    area: 'System',
    navHref: '/system',
    anchorId: 'system-tab-general',
    pose: 'point',
    uaIntent: 'General',
  },
  {
    id: 'help-adm-system-email',
    title: 'Email',
    body: 'SMTP status and test welcome mail.',
    area: 'System',
    navHref: '/system',
    anchorId: 'system-tab-email',
    pose: 'point',
    uaIntent: 'Email / SMTP',
  },
  {
    id: 'help-adm-system-dictionary',
    title: 'Word dictionary',
    body: 'Dictionary and translation providers for vocabulary enrichment.',
    area: 'System',
    navHref: '/system',
    anchorId: 'system-tab-dictionary',
    pose: 'point',
    uaIntent: 'Dictionary',
  },
  {
    id: 'help-adm-system-connections',
    title: 'Connections',
    body: 'Google, Zoom, LiveKit, and related integrations. Teachers also link accounts under Profile → Connections.',
    area: 'System',
    navHref: '/system',
    anchorId: 'system-tab-connections',
    pose: 'point',
    uaIntent: 'Connections',
  },
  {
    id: 'help-adm-system-payments',
    title: 'Payments for students',
    body: 'Currencies, methods, packages, manual invoice templates, and secrets — required for student /payment to work.',
    area: 'System',
    navHref: '/system',
    anchorId: 'system-tab-payments-trigger',
    pose: 'point',
    uaIntent: 'System Payments',
  },
  {
    id: 'help-adm-system-payouts',
    title: 'Payouts',
    body: 'Staff payout defaults — pair with Finance when recording payouts.',
    area: 'System',
    navHref: '/system',
    anchorId: 'system-tab-payouts',
    pose: 'point',
    uaIntent: 'System Payouts',
  },
  {
    id: 'help-adm-system-domains',
    title: 'Domains',
    body: 'Custom school domain setup.',
    area: 'System',
    navHref: '/system',
    anchorId: 'system-tab-domains',
    pose: 'point',
    uaIntent: 'Domains',
  },
  {
    id: 'help-adm-system-branding',
    title: 'Branding',
    body: 'School branding and accent (wizard may already have set accent).',
    area: 'System',
    navHref: '/system',
    anchorId: 'system-tab-branding',
    pose: 'point',
    uaIntent: 'Branding',
  },
  // /materials
  {
    id: 'help-adm-materials-grid',
    title: 'School library',
    body: 'Shared library for the school; quota tied to Subscription.',
    area: 'Materials',
    navHref: '/materials',
    anchorId: 'materials-grid',
    pose: 'point',
    uaIntent: 'Бібліотека',
  },
  {
    id: 'help-adm-materials-create',
    title: 'Add material',
    body: 'Create reusable assets teachers attach to lessons.',
    area: 'Materials',
    navHref: '/materials',
    anchorId: 'materials-create',
    pose: 'point',
    uaIntent: 'Створити',
  },
  {
    id: 'help-adm-materials-upload',
    title: 'Upload',
    body: 'Files ≤100MB; watch storage entitlements.',
    area: 'Materials',
    navHref: '/materials',
    anchorId: 'materials-upload',
    pose: 'point',
    uaIntent: 'Upload',
  },
  {
    id: 'help-adm-materials-viewer',
    title: 'Viewer',
    body: 'In-app book/media viewer.',
    area: 'Materials',
    navHref: '/materials',
    anchorId: 'materials-viewer',
    pose: 'point',
    uaIntent: 'Viewer',
  },
  // /calendar
  {
    id: 'help-adm-cal-toolbar',
    title: 'Filters & views',
    body: 'Audience (all / my-students) and teacher filters plus week/month.',
    area: 'Calendar',
    navHref: '/calendar',
    anchorId: 'calendar-toolbar',
    pose: 'point',
    uaIntent: 'Тулбар + фільтри',
  },
  {
    id: 'help-adm-cal-grid',
    title: 'School schedule',
    body: 'Whole-school board; admins can plan lessons too.',
    area: 'Calendar',
    navHref: '/calendar',
    anchorId: 'calendar-grid',
    pose: 'point',
    uaIntent: 'Сітка',
  },
  {
    id: 'help-adm-cal-create',
    title: 'New lesson',
    body: 'Same create modal as teachers.',
    area: 'Calendar',
    navHref: '/calendar',
    anchorId: 'header-create-lesson',
    pose: 'point',
    uaIntent: 'Створити урок',
  },
  // /chat
  {
    id: 'help-adm-chat-inbox',
    title: 'Inbox',
    body: 'School messaging; visibility rules differ by role.',
    area: 'Chat',
    navHref: '/chat',
    anchorId: 'chat-inbox',
    pose: 'point',
    uaIntent: 'Інбокс',
  },
  {
    id: 'help-adm-chat-new',
    title: 'New message',
    body: 'Start a DM.',
    area: 'Chat',
    navHref: '/chat',
    anchorId: 'chat-new-message',
    pose: 'point',
    uaIntent: 'DM',
  },
  {
    id: 'help-adm-chat-group',
    title: 'Create group',
    body: 'Admins can create group chats.',
    area: 'Chat',
    navHref: '/chat',
    anchorId: 'chat-create-group',
    pose: 'point',
    uaIntent: 'Груповий чат',
  },
  {
    id: 'help-adm-chat-composer',
    title: 'Thread',
    body: 'Reply and attachments (24h TTL).',
    area: 'Chat',
    navHref: '/chat',
    anchorId: 'chat-composer',
    pose: 'point',
    uaIntent: 'Композер',
  },
  // lessons / practice / profile
  {
    id: 'help-adm-lessons-list',
    title: 'Lessons',
    body: 'Admins can open the lessons list like staff.',
    area: 'Lessons',
    navHref: '/lessons',
    anchorId: 'lessons-list',
    pose: 'point',
    uaIntent: 'Уроки',
  },
  {
    id: 'help-adm-lessons-highlights',
    title: 'Highlights',
    body: 'Next/previous lesson cards.',
    area: 'Lessons',
    navHref: '/lessons',
    anchorId: 'lessons-highlights',
    pose: 'point',
    uaIntent: 'Хайлайти',
  },
  {
    id: 'help-adm-lesson-homework',
    title: 'Homework',
    body: 'Review submissions when you teach.',
    area: 'Lessons',
    navHref: '/lessons',
    anchorId: 'lesson-homework',
    pose: 'point',
    uaIntent: 'ДЗ',
  },
  // /practice + modes (same surfaces as students; staff assign from student profiles)
  {
    id: 'help-adm-practice-hub',
    title: 'Practice hub',
    body: 'Preview all learner modes here. Assign vocabulary, quizzes, or speaking from a student’s Practice tab — not from this hub alone.',
    area: 'Practice',
    navHref: '/practice',
    anchorId: 'practice-hub-cards',
    pose: 'point',
    uaIntent: 'Хаб практики',
  },
  {
    id: 'help-adm-practice-stats',
    title: 'Week stats',
    body: 'When you practice as staff, week activity shows here the same way it does for learners.',
    area: 'Practice',
    navHref: '/practice',
    anchorId: 'practice-stats',
    pose: 'point',
    uaIntent: 'Статистика тижня',
  },
  {
    id: 'help-adm-practice-vocab',
    title: 'Vocabulary',
    body: 'Open Vocabulary to preview list, flashcards, and Play. Assign decks from the student’s Practice tab.',
    area: 'Vocabulary',
    navHref: '/practice',
    anchorId: 'practice-card-vocabulary',
    pose: 'point',
    uaIntent: 'Картка Vocabulary',
  },
  {
    id: 'help-adm-vocab-modes',
    title: 'List · Flashcards · Play',
    body: 'Switch study modes while previewing a deck. Play needs enough cards — same rules as for learners.',
    area: 'Vocabulary',
    navHref: '/vocabulary',
    anchorId: 'vocab-mode-toggle',
    pose: 'point',
    uaIntent: 'Режими словника',
  },
  {
    id: 'help-adm-vocab-stats',
    title: 'Deck stats',
    body: 'New / review / learned counts for the deck you are previewing.',
    area: 'Vocabulary',
    navHref: '/vocabulary',
    anchorId: 'vocab-stats',
    pose: 'point',
    uaIntent: 'Статистика колоди',
  },
  {
    id: 'help-adm-vocab-add',
    title: 'Add a word',
    body: 'Staff can try the add-word flow; learner decks are usually filled from lessons or assignments.',
    area: 'Vocabulary',
    navHref: '/vocabulary',
    anchorId: 'vocab-add-word',
    pose: 'point',
    uaIntent: 'Додати слово',
  },
  {
    id: 'help-adm-vocab-filters',
    title: 'Search & filters',
    body: 'Find words by text, lesson, or part of speech while previewing a deck.',
    area: 'Vocabulary',
    navHref: '/vocabulary',
    anchorId: 'vocab-filters',
    pose: 'point',
    uaIntent: 'Фільтри словника',
  },
  {
    id: 'help-adm-vocab-list',
    title: 'Card grid',
    body: 'Preview learner cards and statuses. Assign decks from the student’s Practice tab.',
    area: 'Vocabulary',
    navHref: '/vocabulary',
    anchorId: 'vocab-word-list',
    pose: 'point',
    uaIntent: 'Сітка карток',
  },
  {
    id: 'help-adm-vocab-flashcard',
    title: 'Flashcard',
    body: 'Same flip-and-mark flow learners use — useful when checking what students see.',
    area: 'Vocabulary',
    navHref: '/vocabulary',
    anchorId: 'vocab-flashcard',
    pose: 'point',
    uaIntent: 'Флешкартка',
  },
  {
    id: 'help-adm-vocab-play-setup',
    title: 'Play setup',
    body: 'Preview Play setup: choose a source, then start when the pool has enough cards.',
    area: 'Vocabulary',
    navHref: '/vocabulary',
    anchorId: 'vocab-play-setup',
    pose: 'point',
    uaIntent: 'Підготовка Play',
  },
  {
    id: 'help-adm-vocab-play-source',
    title: 'Word source',
    body: 'Random, last lesson, or a specific lesson — same controls learners get.',
    area: 'Vocabulary',
    navHref: '/vocabulary',
    anchorId: 'vocab-play-source',
    pose: 'point',
    uaIntent: 'Джерело слів',
  },
  {
    id: 'help-adm-vocab-play-start',
    title: 'Start Play',
    body: 'Begins a multiple-choice preview round.',
    area: 'Vocabulary',
    navHref: '/vocabulary',
    anchorId: 'vocab-play-start',
    pose: 'point',
    uaIntent: 'Старт Play',
  },
  {
    id: 'help-adm-vocab-play-progress',
    title: 'Round progress',
    body: 'Question number and score dots during a Play round.',
    area: 'Vocabulary',
    navHref: '/vocabulary',
    anchorId: 'vocab-play-progress',
    pose: 'point',
    uaIntent: 'Прогрес раунду',
  },
  {
    id: 'help-adm-vocab-play-question',
    title: 'Prompt',
    body: 'The English word shown during Play.',
    area: 'Vocabulary',
    navHref: '/vocabulary',
    anchorId: 'vocab-play-question',
    pose: 'point',
    uaIntent: 'Питання',
  },
  {
    id: 'help-adm-vocab-play-options',
    title: 'Answer choices',
    body: 'Multiple-choice options — same interaction as for learners.',
    area: 'Vocabulary',
    navHref: '/vocabulary',
    anchorId: 'vocab-play-options',
    pose: 'point',
    uaIntent: 'Варіанти відповіді',
  },
  {
    id: 'help-adm-vocab-play-actions',
    title: 'Check · Next · Finish',
    body: 'Confirm, advance, or end the round early.',
    area: 'Vocabulary',
    navHref: '/vocabulary',
    anchorId: 'vocab-play-actions',
    pose: 'point',
    uaIntent: 'Дії раунду',
  },
  {
    id: 'help-adm-vocab-play-result',
    title: 'Round results',
    body: 'Score summary and New round after Play finishes.',
    area: 'Vocabulary',
    navHref: '/vocabulary',
    anchorId: 'vocab-play-result',
    pose: 'point',
    uaIntent: 'Результат раунду',
  },
  {
    id: 'help-adm-practice-quiz',
    title: 'Quizzes',
    body: 'Open Quiz to preview assigned vs practice runs. Generate quizzes for students from the quiz hub when available.',
    area: 'Quiz',
    navHref: '/practice',
    anchorId: 'practice-card-quiz',
    pose: 'point',
    uaIntent: 'Вікторини',
  },
  {
    id: 'help-adm-quiz-hero',
    title: 'Quiz session',
    body: 'Inside a quiz: answer flow matches learners. Staff can also generate quizzes when the generate control is available.',
    area: 'Quiz',
    navHref: '/quiz',
    anchorId: 'quiz-hero',
    pose: 'point',
    uaIntent: 'Сесія квізу',
  },
  {
    id: 'help-adm-quiz-generate',
    title: 'Generate quizzes',
    body: 'Create quizzes for learners from the quiz hub. Assign them from the student’s Practice tab.',
    area: 'Quiz',
    navHref: '/quiz',
    anchorId: 'quiz-generate',
    pose: 'point',
    uaIntent: 'Генерація квізів',
  },
  {
    id: 'help-adm-practice-speaking',
    title: 'Speaking',
    body: 'Preview speaking topics and recording. Assign topics and review submissions from the student’s Practice tab.',
    area: 'Speaking',
    navHref: '/practice',
    anchorId: 'practice-card-speaking',
    pose: 'point',
    uaIntent: 'Speaking',
  },
  {
    id: 'help-adm-speaking-record',
    title: 'Record a reply',
    body: 'Mic permission is required to record. Teachers and admins review learner submissions later.',
    area: 'Speaking',
    navHref: '/practice/speaking',
    anchorId: 'speaking-record',
    pose: 'point',
    uaIntent: 'Запис Speaking',
  },
  {
    id: 'help-adm-practice-irregular',
    title: 'Irregular verbs',
    body: 'Three-forms drill for preview. Results are not saved to a vocabulary deck; they count toward practice week time.',
    area: 'Irregular verbs',
    navHref: '/practice',
    anchorId: 'practice-card-irregular',
    pose: 'point',
    uaIntent: 'Неправильні дієслова',
  },
  {
    id: 'help-adm-irregular-play',
    title: 'Start a drill',
    body: 'Pick a tier, then Play. Same drill learners use — useful when checking what students see.',
    area: 'Irregular verbs',
    navHref: '/practice/irregular-verbs',
    anchorId: 'irregular-play',
    pose: 'point',
    uaIntent: 'Старт drill',
  },
  {
    id: 'help-adm-profile-account',
    title: 'Account & Help',
    body: 'Learning mode, Replay tour, logout.',
    area: 'Profile',
    navHref: '/profile',
    anchorId: 'profile-tab-account',
    pose: 'point',
    uaIntent: 'Account',
  },
  {
    id: 'help-adm-profile-connections',
    title: 'Your connections',
    body: 'Personal OAuth links for video hosting when you teach.',
    area: 'Profile',
    navHref: '/profile',
    anchorId: 'profile-connections',
    pose: 'point',
    uaIntent: 'Connections',
  },
];
