import type { TourStep } from './types';

/**
 * Student Help encyclopedia (Header `?`) — page-scoped tips from TZ §4.13.3.
 * Filtered by pathname / modal anchors; never resets tourCompletedAt.
 */
export const STUDENT_HELP_STEPS: TourStep[] = [
  // /dashboard
  {
    id: 'help-stu-dash-hero',
    title: 'Your next step',
    body: 'The hero banner points at the most useful action right now — a lesson, word review, or practice. Tap it when you are not sure where to start.',
    area: 'Dashboard',
    navHref: '/dashboard',
    anchorId: 'dash-hero',
    pose: 'point',
    uaIntent: 'Герой-банер: наступна дія',
  },
  {
    id: 'help-stu-dash-quick-actions',
    title: 'Quick actions',
    body: 'Shortcuts to Calendar, Practice, Vocabulary, Chat, and Quizzes. Badges mean something is waiting in Practice or Chat.',
    area: 'Dashboard',
    navHref: '/dashboard',
    anchorId: 'dash-quick-actions',
    pose: 'point',
    uaIntent: 'Швидкі дії + бейджі',
  },
  {
    id: 'help-stu-dash-stats',
    title: 'Your stats',
    body: 'Tiles show vocabulary cards, lessons today, and completed lessons — a quick pulse of your week.',
    area: 'Dashboard',
    navHref: '/dashboard',
    anchorId: 'dash-stats',
    pose: 'point',
    uaIntent: 'Плитки статистики',
  },
  {
    id: 'help-stu-dash-today',
    title: "Today's lessons",
    body: 'Lessons scheduled for today. Open a card to enter the lesson room for plan, materials, and homework.',
    area: 'Dashboard',
    navHref: '/dashboard',
    anchorId: 'dash-today-lessons',
    pose: 'point',
    uaIntent: 'Уроки сьогодні',
  },
  {
    id: 'help-stu-dash-upcoming',
    title: 'Coming up',
    body: 'Upcoming lessons beyond today so you can plan ahead.',
    area: 'Dashboard',
    navHref: '/dashboard',
    anchorId: 'dash-upcoming',
    pose: 'point',
    uaIntent: 'Найближчі уроки',
  },
  {
    id: 'help-stu-dash-review',
    title: 'Review words',
    body: 'Cards due for review. Jump into Vocabulary Play when you have a few minutes.',
    area: 'Dashboard',
    navHref: '/dashboard',
    anchorId: 'dash-review-words',
    pose: 'point',
    uaIntent: 'Слова на повторення',
  },
  {
    id: 'help-stu-dash-daily-goals',
    title: 'Daily goals',
    body: 'Small targets to keep your streak alive. Check them off after you practice or review words.',
    area: 'Dashboard',
    navHref: '/dashboard',
    anchorId: 'dash-daily-goals',
    pose: 'point',
    uaIntent: 'Щоденні цілі',
  },
  {
    id: 'help-stu-dash-wotd',
    title: 'Word of the day',
    body: 'A daily word tip. Open it when you want a quick vocabulary boost.',
    area: 'Dashboard',
    navHref: '/dashboard',
    anchorId: 'dash-word-of-day',
    pose: 'point',
    uaIntent: 'Слово дня',
  },
  {
    id: 'help-stu-dash-streak',
    title: 'Streak calendar',
    body: 'Your practice streak over recent days. Consistency matters more than long sessions.',
    area: 'Dashboard',
    navHref: '/dashboard',
    anchorId: 'dash-streak',
    pose: 'point',
    uaIntent: 'Календар стріку',
  },
  {
    id: 'help-stu-dash-irregular',
    title: 'Irregular verb of the day',
    body: 'A daily irregular verb tip. Open Irregular verbs from Practice to drill all three forms.',
    area: 'Dashboard',
    navHref: '/dashboard',
    anchorId: 'dash-irregular-verb',
    pose: 'point',
    uaIntent: 'Дієслово дня',
  },
  // /lessons
  {
    id: 'help-stu-lessons-highlights',
    title: 'Next & previous',
    body: 'Highlight cards show your next and previous lessons with materials count and homework status.',
    area: 'Lessons',
    navHref: '/lessons',
    anchorId: 'lessons-highlights',
    pose: 'point',
    uaIntent: 'Хайлайти уроків',
  },
  {
    id: 'help-stu-lessons-list',
    title: 'Lessons list',
    body: 'Full schedule with filters. There is no separate Homework page — homework lives on each lesson.',
    area: 'Lessons',
    navHref: '/lessons',
    anchorId: 'lessons-list',
    pose: 'point',
    uaIntent: 'Список уроків / ДЗ',
  },
  {
    id: 'help-stu-lesson-join',
    title: 'Join video',
    body: 'When the lesson is live and your school video provider is ready, join Meet, Zoom, or LiveKit from the lesson room.',
    area: 'Lessons',
    navHref: '/lessons',
    anchorId: 'lesson-join-video',
    pose: 'point',
    uaIntent: 'Відео-дзвінок',
  },
  {
    id: 'help-stu-lesson-homework',
    title: 'Homework',
    body: 'Submit homework only after the lesson is marked completed. Until then it stays “Opens after the lesson”.',
    area: 'Lessons',
    navHref: '/lessons',
    anchorId: 'lesson-homework',
    pose: 'point',
    uaIntent: 'ДЗ після завершення',
  },
  // /practice
  {
    id: 'help-stu-practice-hub',
    title: 'Practice hub',
    body: 'Your skill gym. Four modes are live: Vocabulary, Quiz, Speaking, and Irregular verbs. Games and Challenges are coming soon — ignore them for now.',
    area: 'Practice',
    navHref: '/practice',
    anchorId: 'practice-hub-cards',
    pose: 'point',
    uaIntent: 'Хаб практики',
  },
  {
    id: 'help-stu-practice-stats',
    title: 'Week stats',
    body: 'Time and activity for this week across practice modes.',
    area: 'Practice',
    navHref: '/practice',
    anchorId: 'practice-stats',
    pose: 'point',
    uaIntent: 'Статистика тижня',
  },
  {
    id: 'help-stu-practice-vocab',
    title: 'Vocabulary deck',
    body: 'Open Vocabulary for list, flashcards, or Play. Add words here or from a lesson. Play needs at least a couple of cards.',
    area: 'Vocabulary',
    navHref: '/practice',
    anchorId: 'practice-card-vocabulary',
    pose: 'point',
    uaIntent: 'Картка Vocabulary',
  },
  {
    id: 'help-stu-vocab-modes',
    title: 'List · Flashcards · Play',
    body: 'Switch how you study. Play is a quick multiple-choice round when you have enough cards.',
    area: 'Vocabulary',
    navHref: '/vocabulary',
    anchorId: 'vocab-mode-toggle',
    pose: 'point',
    uaIntent: 'Режими словника',
  },
  {
    id: 'help-stu-vocab-stats',
    title: 'Deck stats',
    body: 'Totals for new, review, and learned cards. Tap a chip to filter the list.',
    area: 'Vocabulary',
    navHref: '/vocabulary',
    anchorId: 'vocab-stats',
    pose: 'point',
    uaIntent: 'Статистика колоди',
  },
  {
    id: 'help-stu-vocab-add',
    title: 'Add a word',
    body: 'Type an English word to look it up and add it to your deck. You can also save words from lessons.',
    area: 'Vocabulary',
    navHref: '/vocabulary',
    anchorId: 'vocab-add-word',
    pose: 'point',
    uaIntent: 'Додати слово',
  },
  {
    id: 'help-stu-vocab-filters',
    title: 'Search & filters',
    body: 'Find words by text, lesson, or part of speech. Filters apply to List and Flashcards.',
    area: 'Vocabulary',
    navHref: '/vocabulary',
    anchorId: 'vocab-filters',
    pose: 'point',
    uaIntent: 'Фільтри словника',
  },
  {
    id: 'help-stu-vocab-list',
    title: 'Your cards',
    body: 'Each card shows status and actions. Open a word for details; mark status as you learn.',
    area: 'Vocabulary',
    navHref: '/vocabulary',
    anchorId: 'vocab-word-list',
    pose: 'point',
    uaIntent: 'Сітка карток',
  },
  {
    id: 'help-stu-vocab-flashcard',
    title: 'Flashcard',
    body: 'Tap to flip. Mark how well you know the word, then move to the next card.',
    area: 'Vocabulary',
    navHref: '/vocabulary',
    anchorId: 'vocab-flashcard',
    pose: 'point',
    uaIntent: 'Флешкартка',
  },
  {
    id: 'help-stu-vocab-play-setup',
    title: 'Play setup',
    body: 'Choose a word source, then start when you have at least two usable cards.',
    area: 'Vocabulary',
    navHref: '/vocabulary',
    anchorId: 'vocab-play-setup',
    pose: 'point',
    uaIntent: 'Підготовка Play',
  },
  {
    id: 'help-stu-vocab-play-source',
    title: 'Word source',
    body: 'Random, last lesson, or a specific lesson — picks which cards enter the round.',
    area: 'Vocabulary',
    navHref: '/vocabulary',
    anchorId: 'vocab-play-source',
    pose: 'point',
    uaIntent: 'Джерело слів',
  },
  {
    id: 'help-stu-vocab-play-start',
    title: 'Start Play',
    body: 'Begins a multiple-choice round. Needs enough cards in the selected pool.',
    area: 'Vocabulary',
    navHref: '/vocabulary',
    anchorId: 'vocab-play-start',
    pose: 'point',
    uaIntent: 'Старт Play',
  },
  {
    id: 'help-stu-vocab-play-progress',
    title: 'Round progress',
    body: 'Question number and score dots update as you answer.',
    area: 'Vocabulary',
    navHref: '/vocabulary',
    anchorId: 'vocab-play-progress',
    pose: 'point',
    uaIntent: 'Прогрес раунду',
  },
  {
    id: 'help-stu-vocab-play-question',
    title: 'Prompt',
    body: 'The English word (and phonetic) you need to translate.',
    area: 'Vocabulary',
    navHref: '/vocabulary',
    anchorId: 'vocab-play-question',
    pose: 'point',
    uaIntent: 'Питання',
  },
  {
    id: 'help-stu-vocab-play-options',
    title: 'Answer choices',
    body: 'Pick one translation, then Check. Wrong answers can send the card back to review.',
    area: 'Vocabulary',
    navHref: '/vocabulary',
    anchorId: 'vocab-play-options',
    pose: 'point',
    uaIntent: 'Варіанти відповіді',
  },
  {
    id: 'help-stu-vocab-play-actions',
    title: 'Check · Next · Finish',
    body: 'Check confirms your pick. Next advances. Finish ends the round early if you need to stop.',
    area: 'Vocabulary',
    navHref: '/vocabulary',
    anchorId: 'vocab-play-actions',
    pose: 'point',
    uaIntent: 'Дії раунду',
  },
  {
    id: 'help-stu-vocab-play-result',
    title: 'Round results',
    body: 'See your score and start a new round when you are ready.',
    area: 'Vocabulary',
    navHref: '/vocabulary',
    anchorId: 'vocab-play-result',
    pose: 'point',
    uaIntent: 'Результат раунду',
  },
  {
    id: 'help-stu-practice-quiz',
    title: 'Quizzes',
    body: 'Start assigned quizzes (saved) or Practice mode (no persist). Wrong answers can send words back into review.',
    area: 'Quiz',
    navHref: '/practice',
    anchorId: 'practice-card-quiz',
    pose: 'point',
    uaIntent: 'Вікторини',
  },
  {
    id: 'help-stu-quiz-hero',
    title: 'Quiz session',
    body: 'Inside a quiz: answer, see feedback, finish to save progress when it is an assigned quiz.',
    area: 'Quiz',
    navHref: '/quiz',
    anchorId: 'quiz-hero',
    pose: 'point',
    uaIntent: 'Сесія квізу',
  },
  {
    id: 'help-stu-practice-speaking',
    title: 'Speaking',
    body: 'Record answers to topics your teacher assigns. Mic permission is required. Teachers review submissions later.',
    area: 'Speaking',
    navHref: '/practice',
    anchorId: 'practice-card-speaking',
    pose: 'point',
    uaIntent: 'Speaking',
  },
  {
    id: 'help-stu-speaking-record',
    title: 'Record a reply',
    body: 'Open an assigned topic and record your answer. Mic permission is required. Teachers review submissions later.',
    area: 'Speaking',
    navHref: '/practice/speaking',
    anchorId: 'speaking-record',
    pose: 'point',
    uaIntent: 'Запис Speaking',
  },
  {
    id: 'help-stu-practice-irregular',
    title: 'Irregular verbs',
    body: 'Drill three forms. Results are not saved to your vocabulary deck but count toward practice week time.',
    area: 'Irregular verbs',
    navHref: '/practice',
    anchorId: 'practice-card-irregular',
    pose: 'point',
    uaIntent: 'Неправильні дієслова',
  },
  {
    id: 'help-stu-irregular-play',
    title: 'Start a drill',
    body: 'Pick a tier, then start Play to practice irregular verb forms. Results count toward practice week time but do not add vocabulary cards.',
    area: 'Irregular verbs',
    navHref: '/practice/irregular-verbs',
    anchorId: 'irregular-play',
    pose: 'point',
    uaIntent: 'Старт drill',
  },
  // /calendar
  {
    id: 'help-stu-cal-toolbar',
    title: 'Week or month',
    body: 'Toggle week and month views and move between dates. Your timezone comes from Profile.',
    area: 'Calendar',
    navHref: '/calendar',
    anchorId: 'calendar-toolbar',
    pose: 'point',
    uaIntent: 'Тулбар календаря',
  },
  {
    id: 'help-stu-cal-grid',
    title: 'Schedule board',
    body: 'Browse lessons on the grid. Open a lesson to see details; you cannot drag or create slots as a student.',
    area: 'Calendar',
    navHref: '/calendar',
    anchorId: 'calendar-grid',
    pose: 'point',
    uaIntent: 'Сітка календаря',
  },
  {
    id: 'help-stu-cal-request',
    title: 'Request a lesson',
    body: 'Ask your teacher for a time — this opens Chat with that teacher so you can arrange it.',
    area: 'Calendar',
    navHref: '/calendar',
    anchorId: 'calendar-request-lesson',
    pose: 'point',
    uaIntent: 'Запит уроку → чат',
  },
  // /chat
  {
    id: 'help-stu-chat-inbox',
    title: 'Inbox',
    body: 'Threads with your teachers and school admins. Unread shows on the nav badge.',
    area: 'Chat',
    navHref: '/chat',
    anchorId: 'chat-inbox',
    pose: 'point',
    uaIntent: 'Інбокс',
  },
  {
    id: 'help-stu-chat-new',
    title: 'New message',
    body: 'Start a DM with someone you are allowed to message (assigned teachers and admins).',
    area: 'Chat',
    navHref: '/chat',
    anchorId: 'chat-new-message',
    pose: 'point',
    uaIntent: 'Нове повідомлення',
  },
  {
    id: 'help-stu-chat-composer',
    title: 'Message & attach',
    body: 'Type in the thread. Attachments expire after 24 hours — download anything you need to keep.',
    area: 'Chat',
    navHref: '/chat',
    anchorId: 'chat-composer',
    pose: 'point',
    uaIntent: 'Композер + вкладення',
  },
  // /payment
  {
    id: 'help-stu-payment-balance',
    title: 'Lesson balance',
    body: 'Prepaid lessons you can spend. This is **not** the school’s SaaS subscription.',
    area: 'Payment',
    navHref: '/payment',
    anchorId: 'payment-balance',
    pose: 'point',
    uaIntent: 'Баланс уроків',
  },
  {
    id: 'help-stu-payment-packages',
    title: 'Packages',
    body: 'Buy a package when your school enabled self-serve checkout and configured payment methods.',
    area: 'Payment',
    navHref: '/payment',
    anchorId: 'payment-packages',
    pose: 'point',
    uaIntent: 'Пакети',
  },
  {
    id: 'help-stu-payment-methods',
    title: 'How to pay',
    body: 'Online methods and/or manual invoice (IBAN) depending on System → Payments at your school.',
    area: 'Payment',
    navHref: '/payment',
    anchorId: 'payment-methods',
    pose: 'point',
    uaIntent: 'Методи оплати',
  },
  {
    id: 'help-stu-payment-ledger',
    title: 'Activity',
    body: 'History of top-ups and lesson usage on your balance.',
    area: 'Payment',
    navHref: '/payment',
    anchorId: 'payment-ledger',
    pose: 'point',
    uaIntent: 'Історія балансу',
  },
  // /profile
  {
    id: 'help-stu-profile-tab',
    title: 'Profile',
    body: 'Name, avatar, languages, and timezone used for calendar and lessons.',
    area: 'Profile',
    navHref: '/profile',
    anchorId: 'profile-tab-profile',
    pose: 'point',
    uaIntent: 'Вкладка Profile',
  },
  {
    id: 'help-stu-profile-stats',
    title: 'Statistics',
    body: 'Your learning metrics and progress overview.',
    area: 'Profile',
    navHref: '/profile',
    anchorId: 'profile-tab-statistics',
    pose: 'point',
    uaIntent: 'Статистика',
  },
  {
    id: 'help-stu-profile-notifications',
    title: 'Notifications',
    body: 'Email and in-app preferences.',
    area: 'Profile',
    navHref: '/profile',
    anchorId: 'profile-tab-notifications',
    pose: 'point',
    uaIntent: 'Сповіщення',
  },
  {
    id: 'help-stu-profile-connections',
    title: 'Connections',
    body: 'Link Google or other accounts if your school uses them for login or video.',
    area: 'Profile',
    navHref: '/profile',
    anchorId: 'profile-connections-tab',
    pose: 'point',
    uaIntent: 'Connections',
  },
  {
    id: 'help-stu-profile-appearance',
    title: 'Appearance',
    body: 'Theme and font size for the app shell.',
    area: 'Profile',
    navHref: '/profile',
    anchorId: 'profile-tab-appearance',
    pose: 'point',
    uaIntent: 'Appearance',
  },
  {
    id: 'help-stu-profile-account',
    title: 'Account',
    body: 'Password, Learning mode (Header ?), full Replay tour, logout, and data export.',
    area: 'Profile',
    navHref: '/profile',
    anchorId: 'profile-tab-account',
    pose: 'point',
    uaIntent: 'Account / Help',
  },
];
