import type { TourStep } from './types';

/** Student Level A — learning loop + lesson payment (not school SaaS). */
export const STUDENT_TOUR_STEPS: TourStep[] = [
  {
    id: 'stu-welcome',
    title: "Welcome — I'm Arvi",
    body: "Hi! I'll show you around step by step. You can skip anytime and replay later from Profile → Account.",
    pose: 'greet',
    uaIntent: 'Привітання; replay з Profile → Account',
  },
  {
    id: 'stu-dashboard',
    title: 'Your dashboard',
    body: 'This is your daily hub. The top banner points at your next useful action — a lesson, word review, or practice.',
    area: 'Dashboard',
    navHref: '/dashboard',
    anchorId: 'dash-hero',
    pose: 'point',
    uaIntent: 'Дашборд: герой-банер',
  },
  {
    id: 'stu-dashboard-actions',
    title: 'Quick actions',
    body: 'Shortcuts jump to Calendar, Practice, Vocabulary, Chat, and Quizzes. Badges on Practice or Chat mean something is waiting.',
    area: 'Dashboard',
    navHref: '/dashboard',
    anchorId: 'dash-quick-actions',
    pose: 'point',
    uaIntent: 'Швидкі дії + бейджі',
  },
  {
    id: 'stu-daily-goals',
    title: 'Daily goals',
    body: 'Small daily targets keep your streak alive. Check them off from the dashboard when you practice.',
    area: 'Dashboard',
    navHref: '/dashboard',
    anchorId: 'dash-daily-goals',
    pose: 'encourage',
    uaIntent: 'Щоденні цілі',
  },
  {
    id: 'stu-lessons',
    title: 'Lessons list',
    body: 'Your class list — upcoming and past, with homework status on the highlight cards. There is no separate Homework page.',
    area: 'Lessons',
    navHref: '/lessons',
    pose: 'point',
    uaIntent: 'Список уроків / ДЗ статус',
  },
  {
    id: 'stu-lesson-room',
    title: 'Inside a lesson',
    body: 'Open any lesson for the plan, materials, video join, and homework. Homework opens after the lesson is completed. You can also add vocabulary from the lesson.',
    area: 'Lessons',
    navHref: '/lessons',
    pose: 'point',
    uaIntent: 'Кімната уроку: план, файли, відео, ДЗ',
  },
  {
    id: 'stu-practice',
    title: 'Practice hub',
    body: 'Your skill gym. Four modes are live: Vocabulary, Quiz, Speaking, and Irregular verbs. Games and Challenges are coming soon — ignore them for now.',
    area: 'Practice',
    navHref: '/practice',
    anchorId: 'practice-hub-cards',
    pose: 'point',
    uaIntent: 'Хаб практики',
  },
  {
    id: 'stu-vocabulary',
    title: 'Vocabulary deck',
    body: 'From Practice, open Vocabulary for your word cards. Switch List, Flashcards, or Play. Add words here or from a lesson. Play needs at least a couple of cards.',
    area: 'Vocabulary',
    navHref: '/practice',
    anchorId: 'practice-card-vocabulary',
    pose: 'point',
    uaIntent: 'Словник: List / Flashcards / Play',
  },
  {
    id: 'stu-practice-stats',
    title: 'Practice stats',
    body: 'Week stats show how much time you spent practicing. Due reviews and open quizzes also feed the Practice badge.',
    area: 'Practice',
    navHref: '/practice',
    anchorId: 'practice-stats',
    pose: 'point',
    uaIntent: 'Статистика практики',
  },
  {
    id: 'stu-quiz',
    title: 'Quizzes',
    body: 'Quizzes live under Practice too (and /quiz). Finish assigned quizzes to clear the Practice badge. Wrong answers can send words back into review.',
    area: 'Quiz',
    navHref: '/practice',
    pose: 'point',
    uaIntent: 'Квізи з Practice',
  },
  {
    id: 'stu-speaking',
    title: 'Speaking',
    body: 'Speaking topics let you record answers in the browser. Your teacher can leave feedback. Mic permission is required the first time.',
    area: 'Speaking',
    navHref: '/practice',
    pose: 'encourage',
    uaIntent: 'Speaking + mic',
  },
  {
    id: 'stu-irregular',
    title: 'Irregular verbs',
    body: 'Drill V2/V3 forms in a separate catalog — results are not saved to your vocabulary deck, but time still counts toward Practice this week.',
    area: 'Irregular verbs',
    navHref: '/practice',
    pose: 'point',
    uaIntent: 'Неправильні дієслова',
  },
  {
    id: 'stu-calendar',
    title: 'Calendar',
    body: 'Check when your next lesson is in week or month view. Tap a lesson for details.',
    area: 'Calendar',
    navHref: '/calendar',
    pose: 'point',
    uaIntent: 'Розклад week/month',
  },
  {
    id: 'stu-request-lesson',
    title: 'Request a lesson',
    body: 'Need a new slot? Use Request lesson on the calendar — it opens Chat with your teacher. You cannot drag-create lessons yourself.',
    area: 'Calendar',
    navHref: '/calendar',
    anchorId: 'calendar-request-lesson',
    pose: 'point',
    uaIntent: 'Запит уроку через чат',
  },
  {
    id: 'stu-chat',
    title: 'Chat',
    body: 'Message your teacher here. Unread counts show as a badge. Attachments expire after 24 hours. Use New message to start a thread.',
    area: 'Chat',
    navHref: '/chat',
    anchorId: 'chat-new-message',
    pose: 'point',
    uaIntent: 'Чат; вкладення 24 год',
  },
  {
    id: 'stu-payment',
    title: 'Payment & lesson balance',
    body: 'Your lesson credits live here. Buy a package or follow bank instructions. This is not the school\'s SaaS subscription — it\'s how you pay for lessons.',
    area: 'Payment',
    navHref: '/payment',
    anchorId: 'payment-balance',
    pose: 'point',
    uaIntent: 'Баланс уроків ≠ Subscription школи',
  },
  {
    id: 'stu-profile',
    title: 'Profile & settings',
    body: 'Update name, password, notifications, appearance, and linked accounts. Keep your timezone accurate for the calendar.',
    area: 'Profile',
    navHref: '/profile',
    pose: 'point',
    uaIntent: 'Профіль + timezone',
  },
  {
    id: 'stu-done',
    title: "You're ready",
    body: "You've walked every main section. Next, try short scenarios — add words, practice, payment, chat. Replay anytime from Profile → Account.",
    pose: 'celebrate',
    uaIntent: 'Фініш → chapters',
  },
];
