import type { TourChapter } from './types';

/** Student Tour v3 chapters — soft try-it scenarios after Level A. */
export const STUDENT_TOUR_CHAPTERS: TourChapter[] = [
  {
    id: 'stu-ch-practice',
    title: 'Practice round',
    body: 'Open Practice → Vocabulary. Flashcards or Play is enough — one short peek.',
    area: 'Practice',
    pose: 'encourage',
    steps: [
      {
        id: 'stu-ch-practice-hub',
        level: 'B',
        title: 'Open Practice',
        body: 'Open Practice from the sidebar — your skill gym.',
        area: 'Practice round',
        navHref: '/practice',
        pose: 'encourage',
        sfx: 'encourage',
        softSkipLabel: 'Skip for now',
        requiresAction: {
          id: 'stu-ch-practice-hub',
          hint: 'Open Practice from the sidebar.',
          detects: [{ kind: 'pathname', value: '/practice', match: 'startsWith' }],
        },
        uaIntent: 'Хаб практики',
      },
      {
        id: 'stu-ch-practice-vocab',
        level: 'B',
        title: 'Open Vocabulary',
        body: 'Open Vocabulary from the hub (or /vocabulary). List, Flashcards, or Play — any view counts.',
        area: 'Practice round',
        navHref: '/practice',
        anchorId: 'practice-card-vocabulary',
        pose: 'encourage',
        sfx: 'click',
        softSkipLabel: 'Skip for now',
        requiresAction: {
          id: 'stu-ch-practice-vocab',
          hint: 'Open Vocabulary from Practice.',
          detects: [
            { kind: 'pathname', value: '/vocabulary', match: 'startsWith' },
            { kind: 'pathname', value: '/practice/vocabulary', match: 'startsWith' },
            { kind: 'event', value: 'practice_session_started' },
          ],
        },
        uaIntent: 'Словник',
      },
    ],
  },
  {
    id: 'stu-ch-request-lesson',
    title: 'Request a lesson',
    body: 'Use Request lesson on the calendar, or open Chat with your teacher.',
    area: 'Calendar',
    pose: 'point',
    steps: [
      {
        id: 'stu-ch-request-calendar',
        level: 'B',
        title: 'Open Calendar',
        body: 'Open Calendar to see your schedule.',
        area: 'Request lesson',
        navHref: '/calendar',
        pose: 'point',
        sfx: 'click',
        softSkipLabel: 'Skip for now',
        requiresAction: {
          id: 'stu-ch-request-calendar',
          hint: 'Open Calendar from the sidebar.',
          detects: [{ kind: 'pathname', value: '/calendar', match: 'startsWith' }],
        },
        uaIntent: 'Календар',
      },
      {
        id: 'stu-ch-request-cta',
        level: 'B',
        title: 'Request lesson',
        body: 'Find Request lesson on the calendar — it opens Chat. Opening Chat alone also counts.',
        area: 'Request lesson',
        navHref: '/calendar',
        anchorId: 'calendar-request-lesson',
        pose: 'point',
        sfx: 'click',
        softSkipLabel: 'Skip for now',
        requiresAction: {
          id: 'stu-ch-request-cta',
          hint: 'Find Request lesson, or open Chat.',
          detects: [
            { kind: 'selector', value: '[data-tour-anchor="calendar-request-lesson"]' },
            { kind: 'pathname', value: '/chat', match: 'startsWith' },
          ],
        },
        uaIntent: 'Request lesson CTA',
      },
    ],
  },
  {
    id: 'stu-ch-payment',
    title: 'Lesson balance',
    body: 'Open Payment to see lesson credits. This is not the school’s SaaS subscription.',
    area: 'Payment',
    pose: 'point',
    steps: [
      {
        id: 'stu-ch-payment-open',
        level: 'B',
        title: 'Open Payment',
        body: 'Open Payment from the sidebar.',
        area: 'Payment',
        navHref: '/payment',
        pose: 'point',
        sfx: 'click',
        softSkipLabel: 'Skip for now',
        requiresAction: {
          id: 'stu-ch-payment-open',
          hint: 'Open Payment from the sidebar.',
          detects: [{ kind: 'pathname', value: '/payment', match: 'startsWith' }],
        },
        uaIntent: 'Payment',
      },
      {
        id: 'stu-ch-payment-balance',
        level: 'B',
        title: 'Your balance',
        body: 'Find the balance card — packages and bank instructions live nearby.',
        area: 'Payment',
        navHref: '/payment',
        anchorId: 'payment-balance',
        pose: 'point',
        sfx: 'click',
        softSkipLabel: 'Skip for now',
        requiresAction: {
          id: 'stu-ch-payment-balance',
          hint: 'Find your lesson balance on Payment.',
          detects: [{ kind: 'selector', value: '[data-tour-anchor="payment-balance"]' }],
        },
        uaIntent: 'Баланс уроків',
      },
    ],
  },
  {
    id: 'stu-ch-chat',
    title: 'Say hello',
    body: 'Open Chat and find New message — say hi to your teacher when ready.',
    area: 'Chat',
    pose: 'point',
    steps: [
      {
        id: 'stu-ch-chat-open',
        level: 'B',
        title: 'Open Chat',
        body: 'Open Chat from the sidebar.',
        area: 'Chat',
        navHref: '/chat',
        pose: 'point',
        sfx: 'click',
        softSkipLabel: 'Skip for now',
        requiresAction: {
          id: 'stu-ch-chat-open',
          hint: 'Open Chat from the sidebar.',
          detects: [{ kind: 'pathname', value: '/chat', match: 'startsWith' }],
        },
        uaIntent: 'Чат',
      },
      {
        id: 'stu-ch-chat-new',
        level: 'B',
        title: 'New message',
        body: 'Spot New message. You do not have to send anything for this tour.',
        area: 'Chat',
        navHref: '/chat',
        anchorId: 'chat-new-message',
        pose: 'point',
        sfx: 'click',
        softSkipLabel: 'Skip for now',
        requiresAction: {
          id: 'stu-ch-chat-new',
          hint: 'Find New message on Chat.',
          detects: [{ kind: 'selector', value: '[data-tour-anchor="chat-new-message"]' }],
        },
        uaIntent: 'New message',
      },
    ],
  },
];
