import type { TourChapter } from './types';

/** Teacher Tour v3 chapters — soft try-it scenarios after Level A. */
export const TEACHER_TOUR_CHAPTERS: TourChapter[] = [
  {
    id: 'tea-ch-first-lesson',
    title: 'First lesson',
    body: 'Open the create-lesson flow from the header or calendar. Cancel without saving is fine.',
    area: 'Lessons',
    pose: 'point',
    steps: [
      {
        id: 'tea-ch-lesson-open',
        level: 'B',
        title: 'Open New lesson',
        body: 'Click New lesson in the header (or on the calendar). The lesson modal should appear.',
        area: 'First lesson',
        navHref: '/calendar',
        anchorId: 'header-create-lesson',
        pose: 'point',
        sfx: 'click',
        softSkipLabel: 'Skip for now',
        requiresAction: {
          id: 'tea-ch-lesson-open',
          hint: 'Open the New lesson modal.',
          detects: [{ kind: 'selector', value: '[data-tour-anchor="lesson-modal"]' }],
        },
        uaIntent: 'Відкрити модалку уроку',
      },
      {
        id: 'tea-ch-lesson-setup',
        level: 'B',
        title: 'Peek at setup',
        body: 'The Setup tab is where you pick the student, time, and format. Glance at the fields — you can close without saving.',
        area: 'First lesson',
        anchorId: 'lesson-modal-setup',
        pose: 'point',
        sfx: 'click',
        softSkipLabel: 'Skip for now',
        requiresAction: {
          id: 'tea-ch-lesson-setup',
          hint: 'Keep the lesson modal open on Setup (or reopen New lesson).',
          detects: [
            { kind: 'selector', value: '[data-tour-anchor="lesson-modal-setup"]' },
            { kind: 'selector', value: '[data-tour-anchor="lesson-modal"]' },
          ],
        },
        uaIntent: 'Вкладка Setup в модалці',
      },
    ],
  },
  {
    id: 'tea-ch-materials',
    title: 'Materials library',
    body: 'Visit Materials and find the create / upload control. No need to upload a file.',
    area: 'Materials',
    pose: 'point',
    steps: [
      {
        id: 'tea-ch-materials-open',
        level: 'B',
        title: 'Open Materials',
        body: 'Go to Materials from the sidebar — your shared library of boards, books, and media.',
        area: 'Materials',
        navHref: '/materials',
        pose: 'point',
        sfx: 'click',
        softSkipLabel: 'Skip for now',
        requiresAction: {
          id: 'tea-ch-materials-open',
          hint: 'Open Materials from the sidebar.',
          detects: [{ kind: 'pathname', value: '/materials', match: 'startsWith' }],
        },
        uaIntent: 'Відкрити матеріали',
      },
      {
        id: 'tea-ch-materials-create',
        level: 'B',
        title: 'Find create',
        body: 'Spot the create / upload button. Opening the dialog is enough — cancel anytime.',
        area: 'Materials',
        navHref: '/materials',
        anchorId: 'materials-create',
        pose: 'point',
        sfx: 'click',
        softSkipLabel: 'Skip for now',
        requiresAction: {
          id: 'tea-ch-materials-create',
          hint: 'Find the Materials create button (or open the upload dialog).',
          detects: [
            { kind: 'selector', value: '[data-tour-anchor="materials-create"]' },
            { kind: 'selector', value: '[data-tour-anchor="materials-upload"]' },
          ],
        },
        uaIntent: 'Кнопка створення матеріалу',
      },
    ],
  },
  {
    id: 'tea-ch-students',
    title: 'Students & practice',
    body: 'Open your roster, then a student profile if you have one. Practice assignment lives on the student page.',
    area: 'Students',
    pose: 'point',
    steps: [
      {
        id: 'tea-ch-students-roster',
        level: 'B',
        title: 'Open Students',
        body: 'Open Students from the sidebar to see your roster.',
        area: 'Students',
        navHref: '/students',
        pose: 'point',
        sfx: 'click',
        softSkipLabel: 'Skip for now',
        requiresAction: {
          id: 'tea-ch-students-roster',
          hint: 'Open Students from the sidebar.',
          detects: [{ kind: 'pathname', value: '/students', match: 'startsWith' }],
        },
        uaIntent: 'Список учнів',
      },
      {
        id: 'tea-ch-students-card',
        level: 'B',
        title: 'Open a student',
        body: 'If you have learners, open a student card. Empty roster? Skip — your admin can invite someone later.',
        area: 'Students',
        navHref: '/students',
        anchorId: 'student-card',
        pose: 'point',
        sfx: 'click',
        softSkipLabel: 'Skip for now',
        requiresAction: {
          id: 'tea-ch-students-card',
          hint: 'Open a student profile, or skip if the roster is empty.',
          detects: [
            { kind: 'pathname', value: '/students/', match: 'startsWith' },
            { kind: 'selector', value: '[data-tour-anchor="student-card"]' },
          ],
        },
        uaIntent: 'Картка учня',
      },
    ],
  },
  {
    id: 'tea-ch-groups',
    title: 'Groups',
    body: 'When group lessons are on, switch to the Groups tab for shared templates.',
    area: 'Students',
    pose: 'point',
    requiresFeature: 'groupLessons',
    steps: [
      {
        id: 'tea-ch-groups-tab',
        level: 'B',
        title: 'Open Groups',
        body: 'On Students, switch to the Groups tab.',
        area: 'Groups',
        navHref: '/students',
        anchorId: 'students-groups-tab',
        pose: 'point',
        sfx: 'click',
        softSkipLabel: 'Skip for now',
        requiresAction: {
          id: 'tea-ch-groups-tab',
          hint: 'Open Students → Groups.',
          detects: [
            { kind: 'selector', value: '[data-tour-anchor="students-groups-panel"]' },
          ],
        },
        uaIntent: 'Вкладка Groups',
      },
    ],
  },
  {
    id: 'tea-ch-chat',
    title: 'Chat',
    body: 'Open Chat and find New message — keep feedback in one place.',
    area: 'Chat',
    pose: 'point',
    steps: [
      {
        id: 'tea-ch-chat-open',
        level: 'B',
        title: 'Open Chat',
        body: 'Open Chat from the sidebar.',
        area: 'Chat',
        navHref: '/chat',
        pose: 'point',
        sfx: 'click',
        softSkipLabel: 'Skip for now',
        requiresAction: {
          id: 'tea-ch-chat-open',
          hint: 'Open Chat from the sidebar.',
          detects: [{ kind: 'pathname', value: '/chat', match: 'startsWith' }],
        },
        uaIntent: 'Відкрити чат',
      },
      {
        id: 'tea-ch-chat-new',
        level: 'B',
        title: 'Find New message',
        body: 'Spot the New message control — you do not have to send anything.',
        area: 'Chat',
        navHref: '/chat',
        anchorId: 'chat-new-message',
        pose: 'point',
        sfx: 'click',
        softSkipLabel: 'Skip for now',
        requiresAction: {
          id: 'tea-ch-chat-new',
          hint: 'Find New message on Chat.',
          detects: [{ kind: 'selector', value: '[data-tour-anchor="chat-new-message"]' }],
        },
        uaIntent: 'New message',
      },
    ],
  },
  {
    id: 'tea-ch-video',
    title: 'Video setup',
    body: 'Link Google or Zoom under Profile → Connections so you can host video lessons.',
    area: 'Profile',
    pose: 'point',
    steps: [
      {
        id: 'tea-ch-video-profile',
        level: 'B',
        title: 'Open Profile',
        body: 'Open Profile & Settings from the sidebar.',
        area: 'Video setup',
        navHref: '/profile',
        pose: 'point',
        sfx: 'click',
        softSkipLabel: 'Skip for now',
        requiresAction: {
          id: 'tea-ch-video-profile',
          hint: 'Open Profile from the sidebar.',
          detects: [{ kind: 'pathname', value: '/profile', match: 'startsWith' }],
        },
        uaIntent: 'Профіль',
      },
      {
        id: 'tea-ch-video-connections',
        level: 'B',
        title: 'Connections tab',
        body: 'Open the Connections tab to link Google Meet or Zoom. Linking is optional for this tour.',
        area: 'Video setup',
        navHref: '/profile',
        // Spotlight the tab trigger (panel mounts after click).
        anchorId: 'profile-connections-tab',
        pose: 'point',
        sfx: 'click',
        softSkipLabel: 'Skip for now',
        requiresAction: {
          id: 'tea-ch-video-connections',
          hint: 'Open Profile → Connections.',
          detects: [{ kind: 'selector', value: '[data-tour-anchor="profile-connections"]' }],
        },
        uaIntent: 'Connections для відео',
      },
    ],
  },
];
