import type { TourStep } from './types';

/** Teacher Level A — plan, materials, students, feedback. */
export const TEACHER_TOUR_STEPS: TourStep[] = [
  {
    id: 'tea-welcome',
    title: 'Welcome, teacher',
    body: "I'm Arvi. We'll walk through planning, materials, students, and feedback — skip anytime. Replay later from Profile → Account.",
    pose: 'greet',
    uaIntent: 'Привітання вчителя',
  },
  {
    id: 'tea-dashboard',
    title: 'Teaching dashboard',
    body: "Start here each day: today's lessons, homework waiting for review, and shortcuts including New lesson and Students.",
    area: 'Dashboard',
    navHref: '/dashboard',
    anchorId: 'dash-hero',
    pose: 'point',
    uaIntent: 'Дашборд + ДЗ на перевірку',
  },
  {
    id: 'tea-dashboard-homework',
    title: 'Homework to review',
    body: 'When students submit after a completed lesson, items appear in your homework queue on the dashboard. Open a lesson to accept or leave feedback.',
    area: 'Dashboard',
    navHref: '/dashboard',
    anchorId: 'dash-homework-review',
    pose: 'point',
    uaIntent: 'Черга ДЗ на дашборді',
  },
  {
    id: 'tea-dashboard-actions',
    title: 'Quick actions',
    body: 'Shortcuts include Calendar, Students, and New lesson. Use them to jump into planning without hunting the sidebar.',
    area: 'Dashboard',
    navHref: '/dashboard',
    anchorId: 'dash-quick-actions',
    pose: 'point',
    uaIntent: 'Швидкі дії викладача',
  },
  {
    id: 'tea-calendar',
    title: 'Plan on the calendar',
    body: 'Create, move, and resize lessons in week or month view. Conflicts and series edits confirm separately; past slots stay locked.',
    area: 'Calendar',
    navHref: '/calendar',
    pose: 'point',
    uaIntent: 'Календар DnD',
  },
  {
    id: 'tea-calendar-create',
    title: 'New lesson',
    body: 'Use New lesson in the header or on the calendar. The modal has Setup (who/when), Content (materials), and Homework — cancel anytime without saving.',
    area: 'Calendar',
    navHref: '/calendar',
    anchorId: 'header-create-lesson',
    pose: 'point',
    uaIntent: 'Модалка створення уроку + header CTA',
  },
  {
    id: 'tea-lessons',
    title: 'Lessons list',
    body: 'The Lessons page lists your schedule with homework status. Open a card to enter the lesson room.',
    area: 'Lessons',
    navHref: '/lessons',
    pose: 'point',
    uaIntent: 'Список уроків',
  },
  {
    id: 'tea-lesson-room',
    title: 'Lesson room',
    body: 'Inside a lesson: edit the plan, attach library materials, set homework, join video, and review student responses. Students submit homework only after the lesson is completed.',
    area: 'Lessons',
    navHref: '/lessons',
    pose: 'point',
    uaIntent: 'Хаб уроку',
  },
  {
    id: 'tea-materials',
    title: 'Materials library',
    body: 'Upload boards, books, audio, and video once, then attach them to many lessons. Books open in the in-app viewer. Watch storage if your school has a quota.',
    area: 'Materials',
    navHref: '/materials',
    anchorId: 'materials-create',
    pose: 'point',
    uaIntent: 'Бібліотека матеріалів',
  },
  {
    id: 'tea-students',
    title: 'Students roster',
    body: 'Your roster lives here. If the school enabled group lessons, switch to Groups for shared templates.',
    area: 'Students',
    navHref: '/students',
    pose: 'point',
    uaIntent: 'Учні / групи',
  },
  {
    id: 'tea-groups',
    title: 'Groups',
    body: 'Groups hold shared lesson templates and members. Schedule group lessons by picking a named group — not ad-hoc billing.',
    area: 'Students',
    navHref: '/students',
    anchorId: 'students-groups-tab',
    pose: 'point',
    uaIntent: 'Групи (якщо groupLessons увімкнено)',
    requiresFeature: 'groupLessons',
  },
  {
    id: 'tea-student-practice',
    title: 'Assign practice',
    body: 'Open a student → Practice tab to assign vocabulary, quizzes, or speaking. From the student hero you can also jump straight into a DM.',
    area: 'Students',
    navHref: '/students',
    pose: 'point',
    uaIntent: 'Student Practice tab',
  },
  {
    id: 'tea-chat',
    title: 'Chat',
    body: 'Message students and keep feedback in one place. Calendar "request lesson" from a student lands here as a thread with you. Use New message to start a DM.',
    area: 'Chat',
    navHref: '/chat',
    anchorId: 'chat-new-message',
    pose: 'point',
    uaIntent: 'Чат зі студентами',
  },
  {
    id: 'tea-profile',
    title: 'Profile & connections',
    body: 'Your account, appearance, and Connections — link Google or Zoom under the Connections tab so you can host video lessons.',
    area: 'Profile',
    navHref: '/profile',
    pose: 'point',
    uaIntent: 'OAuth для відео',
  },
  {
    id: 'tea-done',
    title: 'Ready to teach',
    body: "You've walked every main section. Next, try short scenarios — lesson draft, materials, and more. Replay anytime from Profile → Account.",
    pose: 'celebrate',
    uaIntent: 'Фініш → chapters',
  },
];
